"""Generated experimental protocol-v2 constants. Do not edit by hand.

Source: protocol/protocol-v2.json
Source SHA-256: d6aae4456917798e439e0f58e8c06555373a7e8dd731586bee3c6fa646245c1c
"""

from __future__ import annotations

from enum import IntEnum, IntFlag

SOURCE_SHA256 = "d6aae4456917798e439e0f58e8c06555373a7e8dd731586bee3c6fa646245c1c"
MAGIC = 0xDEADBEEF
MAGIC_BYTES = b"\xef\xbe\xad\xde"
PROTOCOL_VERSION = 2
BYTE_ORDER = "little"
HEADER_STRUCT_FORMAT = "<IBBHHBBIIIIIQI"
HEADER_SIZE = 44
TRAILER_SIZE = 4
MIN_FRAME_BYTES = 48
DATA_FRAME_BYTES = 4096
MAX_DATA_FRAME_BYTES = 4096
DATA_PAYLOAD_BYTES = 4048
MAX_CONTROL_FRAME_BYTES = 1280
MAX_CONTROL_PAYLOAD_BYTES = MAX_CONTROL_FRAME_BYTES - HEADER_SIZE - TRAILER_SIZE
MAX_COMMAND_FRAME_BYTES = 56
MAX_COMMAND_PAYLOAD_BYTES = 8
TIMESTAMP_HZ = 8000000
ADC_PAIR_RATE_HZ = 1000000
ADC_PAIR_PERIOD_TICKS = 8
ADC1_PHASE_TICKS = 4
GPIO_SAMPLE_RATE_HZ = 4000000
GPIO_SAMPLE_PERIOD_TICKS = 2
FRAME_COVERAGE_TICKS = 8096
SUPPORTED_CONFIGURATION_MASK = 63
ADC_DMA_RING_DEPTH = 8
ADC_PAIRS_PER_BUFFER = 1012
ADC_PAIR_BYTES = 4
ADC_DMA_RING_BYTES = 32512
ADC_EDMA_CHANNELS = (0, 1)
ADC_EDMA_PRIORITIES = (2, 1)
ADC_DMAMUX_SOURCES = (24, 88)
ADC_DMA_IRQ_PRIORITY = 48
GPIO_DMA_IRQ_PRIORITY = 64
PACKET_BUFFER_COUNT = 200
PACKET_PRIMARY_COUNT = 105
PACKET_RESERVE_COUNT = 95
PACKET_READY_QUEUE_CAPACITY = 200
PACKET_TRANSMIT_QUEUE_CAPACITY = 200
COMMAND_QUEUE_CAPACITY = 4
RESPONSE_QUEUE_CAPACITY = 4
NOMINAL_PAYLOAD_BYTES_PER_SECOND_PER_STREAM = 4000000
NOMINAL_FRAMED_BYTES_PER_SECOND_PER_STREAM = 4047431
CHECKSUM_BENCHMARK_CYCLE_COUNTER_HZ = 600000000
CHECKSUM_BENCHMARK_TARGET_FRAMED_BYTES_PER_SECOND = 8100000
CHECKSUM_BENCHMARK_MAX_BATCH_COUNT = 8
CHECKSUM_BENCHMARK_MAX_ITERATIONS_PER_BATCH = 4096
CHECKSUM_BENCHMARK_MAX_OPERATIONS = 32768
CHECKSUM_BENCHMARK_MAX_PROCESSED_BYTES = 8388608
CHECKSUM_BENCHMARK_TIMER_CALIBRATION_SAMPLES = 32
CHECKSUM_BENCHMARK_WARMUP_OPERATIONS = 4
GPIO_CLOCK_PIT_HZ = 24000000
GPIO_CLOCK_DWT_HZ = 600000000
GPIO_CLOCK_PRODUCTION_RATE_HZ = 4000000
GPIO_CLOCK_MIN_RATE_HZ = 1000
GPIO_CLOCK_MIN_EVENT_COUNT = 32
GPIO_CLOCK_MAX_EVENT_COUNT = 8192
GPIO_CLOCK_MAX_ELAPSED_CYCLES = 60000000
GPIO_CLOCK_DUPLICATE_GUARD_EVENTS = 16
GPIO_CLOCK_COUNT_TOLERANCE = 1
GPIO_PACKED_WIDTH_BITS = 8
GPIO_RAW_RING_DEPTH = 4
GPIO_RAW_SAMPLES_PER_BUFFER = 4048
GPIO_RAW_RING_BYTES = 64768
GPIO_PACKED_RING_DEPTH = 4
GPIO_PACKED_RING_BYTES = 16256
GPIO_PACKET_BUFFER_COUNT = 200
GPIO_PIT_CHANNEL = 0
GPIO_XBAR_INPUT = 56
GPIO_XBAR_OUTPUT = 0
GPIO_XBAR_ACTIVE_EDGE = 1
GPIO_EDMA_CHANNEL = 2
GPIO_DMAMUX_SOURCE = 30
GPIO_EDMA_PRIORITY = 0
GPIO_CAPTURE_DIAGNOSTIC_ANALYSIS_SAMPLES = 256
ADC_PRIMARY_RESOLUTION_BITS = 12
ADC_FALLBACK_RESOLUTION_BITS = 10
ADC_CODE_MIN = 0
ADC_REFERENCE_MV_NOMINAL = 3300
ADC_INPUT_MIN_MV_NOMINAL = 0
ADC_INPUT_MAX_MV_NOMINAL = 3300
ADC_IPG_CLOCK_HZ = 150000000
ADC_CLOCK_HZ = 37500000
ADC_CLOCK_DIVIDER = 4
ADC_HARDWARE_AVERAGE_COUNT = 0
ADC_SAMPLE_TIME_ADCK = 3
ADC_CALIBRATION_CYCLE_COUNTER_HZ = 600000000
ADC_CALIBRATION_DEADLINE_US = 10000
ADC_CALIBRATION_POLL_LIMIT = 8000000
ADC_PINS = (14, 15)
ADC_PERIPHERALS = (1, 2)
ADC_CHANNELS = (7, 8)
ADC_TRIGGER_PIT_CLOCK_HZ = 24000000
ADC_TRIGGER_DWT_CLOCK_HZ = 600000000
ADC_TRIGGER_GPIO_MASTER_RATE_HZ = 4000000
ADC_TRIGGER_PAIR_RATE_HZ = 1000000
ADC_TRIGGER_IPG_CLOCK_HZ = 150000000
ADC_TRIGGER_GPIO_MASTER_PIT_CHANNEL = 0
ADC_TRIGGER_PAIR_PIT_CHANNEL = 1
ADC_TRIGGER_GPIO_MASTER_PIT_LOAD = 5
ADC_TRIGGER_PAIR_PIT_LOAD = 3
ADC_TRIGGER_PREDIVIDER = 0
ADC_TRIGGER_CHAIN_LENGTH = 1
ADC_TRIGGER_XBAR_INPUTS = (57, 57)
ADC_TRIGGER_XBAR_OUTPUTS = (103, 107)
ADC_TRIGGER_QUEUES = (0, 4)
ADC_TRIGGER_INITIAL_DELAYS = (0, 75)
ADC_TRIGGER_EFFECTIVE_DELAYS = (1, 76)
ADC_TRIGGER_PHASE_IPG_CYCLES = 75
ADC_COMPLETION_EXPECTED_DWT_CYCLES = 300
ADC_COMPLETION_TOLERANCE_DWT_CYCLES = 120
ADC_TRIGGER_DIAGNOSTIC_DEADLINE_US = 2000
ADC_TRIGGER_DIAGNOSTIC_POLL_LIMIT = 2000000
ADC_TRIGGER_IRQ_PRIORITY = 32
ADC_BYTES_PER_PAIR = 4
ADC_PAIRS_PER_FRAME = 1012
ADC_RESOLUTION_BITS = 12
ADC_CONTAINER_BITS = 16
GPIO_SAMPLES_PER_FRAME = 4048
GPIO_PINS_BY_BIT = (6, 7, 8, 9, 10, 11, 12, 13)
OUTPUT_RATE_HZ = 1000000
OUTPUT_DURATION_QUANTUM_US = 1
OUTPUT_PERIOD_TICKS = 8
OUTPUT_FIRST_EVENT_TICK = 0
OUTPUT_STATE_WIDTH_BITS = 8
OUTPUT_LEGAL_STATE_MASK = 255
OUTPUT_SEGMENT_BYTES = 8
OUTPUT_SEGMENT_CAPACITY = 1024
OUTPUT_MINIMUM_COMMITTED_SEGMENTS = 1
OUTPUT_REPEAT_FOREVER = 0
OUTPUT_PINS_BY_LOGICAL_BIT = (16, 17, 18, 19, 20, 21, 22, 23)
OUTPUT_GPIO_BITS_BY_LOGICAL_BIT = (23, 22, 17, 16, 26, 27, 24, 25)
OUTPUT_GPIO_AGGREGATE_MASK = 264437760
OUTPUT_STANDARD_GPIO = 1
OUTPUT_FAST_GPIO = 6
OUTPUT_FAST_SELECT_GPR = 26
OUTPUT_LOGIC_VOLTAGE_MAX_MV = 3300
OUTPUT_PIT_CHANNEL = 1
OUTPUT_XBAR_INPUT = 57
OUTPUT_XBAR_OUTPUT = 1
OUTPUT_DMAMUX_SOURCE = 31
OUTPUT_EDMA_CHANNEL = 3
OUTPUT_EDMA_PRIORITY = 1
OUTPUT_ADC_EDMA_PRIORITIES = (3, 2)
OUTPUT_GPIO_EDMA_PRIORITY = 0
OUTPUT_DMA_IRQ_NUMBER = 3
OUTPUT_DMA_VECTOR_INDEX = 19
OUTPUT_DMA_IRQ_PRIORITY = 56
OUTPUT_PROGRAM_STORAGE_BYTES = 8192
OUTPUT_DMA_RING_BYTES = 16256
OUTPUT_DMA_DESCRIPTOR_BYTES = 128
OUTPUT_PACKET_PRIMARY_COUNT = 103
OUTPUT_PACKET_RESERVE_COUNT = 91
OUTPUT_PACKET_RETENTION_US = 98164
OUTPUT_PACKET_AND_USB_RETENTION_US = 99176
UINT32_MAX = 0xFFFFFFFF
UINT64_MAX = 0xFFFFFFFFFFFFFFFF


HEADER_MAGIC_OFFSET = 0
HEADER_VERSION_OFFSET = 4
HEADER_KIND_OFFSET = 5
HEADER_FLAGS_OFFSET = 6
HEADER_HEADER_LENGTH_OFFSET = 8
HEADER_CHECKSUM_ALGORITHM_OFFSET = 10
HEADER_RESERVED_OFFSET = 11
HEADER_TOTAL_LENGTH_OFFSET = 12
HEADER_PAYLOAD_LENGTH_OFFSET = 16
HEADER_RUN_ID_OFFSET = 20
HEADER_SEQUENCE_OFFSET = 24
HEADER_REQUEST_ID_OFFSET = 28
HEADER_FIRST_SAMPLE_TICKS_OFFSET = 32
HEADER_ITEM_COUNT_OFFSET = 40


class FrameKind(IntEnum):
    ADC_DATA = 1
    GPIO_DATA = 2
    INFO_REQUEST = 16
    CONFIGURE_REQUEST = 17
    START_REQUEST = 18
    GET_STATUS_REQUEST = 19
    STOP_REQUEST = 20
    RESET_STATS_REQUEST = 21
    PING_REQUEST = 22
    CHECKSUM_BENCHMARK_REQUEST = 23
    GPIO_CLOCK_DIAGNOSTIC_REQUEST = 24
    GPIO_CAPTURE_DIAGNOSTIC_REQUEST = 25
    INFO_RESPONSE = 144
    CONFIGURE_RESPONSE = 145
    START_RESPONSE = 146
    GET_STATUS_RESPONSE = 147
    STOP_RESPONSE = 148
    RESET_STATS_RESPONSE = 149
    PING_RESPONSE = 150
    CHECKSUM_BENCHMARK_RESPONSE = 151
    GPIO_CLOCK_DIAGNOSTIC_RESPONSE = 152
    GPIO_CAPTURE_DIAGNOSTIC_RESPONSE = 153
    OUTPUT_BEGIN_REQUEST = 32
    OUTPUT_BEGIN_RESPONSE = 160
    OUTPUT_APPEND_REQUEST = 33
    OUTPUT_APPEND_RESPONSE = 161
    OUTPUT_COMMIT_REQUEST = 34
    OUTPUT_COMMIT_RESPONSE = 162
    OUTPUT_ARM_REQUEST = 35
    OUTPUT_ARM_RESPONSE = 163
    OUTPUT_STATUS_REQUEST = 36
    OUTPUT_STATUS_RESPONSE = 164
    OUTPUT_CLEAR_REQUEST = 37
    OUTPUT_CLEAR_RESPONSE = 165
    ERROR_RESPONSE = 159


class CommandKind(IntEnum):
    INFO = 16
    CONFIGURE = 17
    START = 18
    GET_STATUS = 19
    STOP = 20
    RESET_STATS = 21
    PING = 22
    CHECKSUM_BENCHMARK = 23
    GPIO_CLOCK_DIAGNOSTIC = 24
    GPIO_CAPTURE_DIAGNOSTIC = 25
    OUTPUT_BEGIN = 32
    OUTPUT_APPEND = 33
    OUTPUT_COMMIT = 34
    OUTPUT_ARM = 35
    OUTPUT_STATUS = 36
    OUTPUT_CLEAR = 37


class FrameFlag(IntFlag):
    NONE = 0
    SYNTHETIC = 1
    GAP_BEFORE = 2
    EPOCH_START = 4
    OVERRUN_BEFORE = 8
    RESPONSE_ERROR = 32768


class ChecksumAlgorithm(IntEnum):
    NONE_RESERVED = 0
    ADLER32 = 1
    CRC32C = 2
    CRC32_ISO_HDLC = 3


class ResponseStatus(IntEnum):
    OK = 0
    ERROR = 1


class ErrorCode(IntEnum):
    OK = 0
    UNSUPPORTED_VERSION = 1
    UNKNOWN_FRAME_KIND = 2
    INVALID_FLAGS = 3
    INVALID_LENGTH = 4
    INVALID_PAYLOAD = 5
    UNSUPPORTED_CHECKSUM = 6
    INVALID_STATE = 7
    UNSUPPORTED_CONFIGURATION = 8
    INVALID_REQUEST_ID = 9
    BUSY = 10
    INTERNAL_ERROR = 11
    CHECKSUM_MISMATCH = 12


class DeviceState(IntEnum):
    BOOT = 0
    IDLE = 1
    CONFIGURED = 2
    RUNNING = 3


class StreamMask(IntFlag):
    NONE = 0
    ADC = 1
    GPIO = 2


class ConfigurationProfile(IntFlag):
    NONE = 0
    HARDWARE_ADC = 1
    HARDWARE_GPIO = 2
    HARDWARE_COMBINED = 4
    SYNTHETIC_ADC = 8
    SYNTHETIC_GPIO = 16
    SYNTHETIC_COMBINED = 32


class Capability(IntFlag):
    NONE = 0
    ADC_STREAM = 1
    GPIO_STREAM = 2
    HARDWARE_SOURCE = 4
    SYNTHETIC_SOURCE = 8
    RESET_STATS = 16
    PING = 32
    CHECKSUM_BENCHMARK = 64
    GPIO_CLOCK_DIAGNOSTIC = 128
    GPIO_CAPTURE_DIAGNOSTIC = 256
    PRELOADED_AUXILIARY_OUTPUT = 512
    COMMON_EPOCH_OUTPUT = 1024


class Source(IntEnum):
    HARDWARE = 0
    SYNTHETIC = 1


class BoardId(IntEnum):
    SIMULATOR = 0
    TEENSY_40 = 1


class McuId(IntEnum):
    SIMULATED = 0
    IMXRT1062 = 1


class BenchmarkVector(IntEnum):
    EMPTY = 0
    CANONICAL_123456789 = 1
    BUFFER_64 = 2
    BUFFER_512 = 3
    FRAME_COVERAGE = 4


class BenchmarkMemoryRegion(IntEnum):
    DTCM_PACKET = 0
    OCRAM_DMA = 1


class BenchmarkCacheState(IntEnum):
    HOT_OR_NATIVE = 0
    COLD_INVALIDATED = 1


class GpioClockError(IntFlag):
    NONE = 0
    DWT_UNAVAILABLE = 1
    RESOURCE_BUSY = 2
    PERCLK_MISMATCH = 4
    PIT_GATE_DISABLED = 8
    XBAR_GATE_DISABLED = 16
    DMA_GATE_DISABLED = 32
    PIT_CONFIG_MISMATCH = 64
    XBAR_CONFIG_MISMATCH = 128
    DMAMUX_CONFIG_MISMATCH = 256
    EDMA_CONFIG_MISMATCH = 512
    EDMA_CHANNEL_ERROR = 1024
    DEAD_TRIGGER = 2048
    DUPLICATE_TRIGGER = 4096
    COUNT_OUT_OF_TOLERANCE = 8192
    MEASUREMENT_OVERFLOW = 16384


class GpioCaptureDiagnosticMode(IntEnum):
    NON_DRIVING_CAPTURE = 0
    SELF_DRIVEN_SWEEP = 1
    FIXTURE_STIMULUS = 2


class GpioCaptureDiagnosticFlag(IntFlag):
    NONE = 0
    AVAILABLE = 1
    DECLARATION_VALID = 2
    OUTPUT_DRIVE_PERMITTED = 4
    EXTERNAL_STIMULUS_DECLARED = 8
    DMA_CAPTURE_EXERCISED = 16
    PACKED_OBSERVATION_EXERCISED = 32
    OUTPUT_DRIVE_EXERCISED = 64
    EXTERNAL_TRANSITION_VALIDATION_EXERCISED = 128
    FINAL_INPUT_SAFE = 256


class GpioCaptureError(IntFlag):
    NONE = 0
    FIXTURE_DECLARATION_INVALID = 1
    UNSUPPORTED_FIXTURE_MODE = 2
    DWT_UNAVAILABLE = 4
    RESOURCE_BUSY = 8
    CAPTURE_TIMEOUT = 16
    CAPTURE_FAULT = 32
    NO_COMPLETE_BUFFER = 64
    DIAGNOSTIC_LEASE_ERROR = 128
    COUNT_MISMATCH = 256
    UNSAFE_CONFIGURED_DIRECTION = 512
    UNSAFE_INPUT_RESTORE = 1024
    MAPPING_MISMATCH = 2048
    UNEXPECTED_OUTPUT_DRIVE = 4096
    EXTERNAL_VALIDATION_MISSING = 8192
    UNEXPECTED_ELECTRICAL_CLAIM = 16384
    CLEANUP_FAILED = 32768


class AdcReference(IntEnum):
    UNSPECIFIED = 0
    VREFH_VREFL_NOMINAL_3V3 = 1


class AdcClockSource(IntEnum):
    UNSPECIFIED = 0
    SYNCHRONOUS_IPG = 1


class AdcCalibrationState(IntEnum):
    NOT_RUN = 0
    SUCCEEDED = 1
    FAILED = 2
    TIMED_OUT = 3
    ROUTE_INVALID = 4
    CONFIGURATION_INVALID = 5
    CLOCK_UNAVAILABLE = 6


class AdcConfigurationFlag(IntFlag):
    NONE = 0
    INITIALIZED = 1
    NO_HARDWARE_AVERAGING = 2
    HIGH_SPEED = 4
    SHORTEST_SAMPLE = 8
    ROUTES_VALIDATED = 16
    CONFIGURATION_READBACK_VALID = 32
    CALIBRATION_COMPLETE = 64
    PRIMARY_12_BIT = 128
    FALLBACK_10_BIT = 256


class AdcInitializationError(IntFlag):
    NONE = 0
    DWT_UNAVAILABLE = 1
    ADC0_ROUTE_INVALID = 2
    ADC1_ROUTE_INVALID = 4
    ADC0_CONFIGURATION_INVALID = 8
    ADC1_CONFIGURATION_INVALID = 16
    ADC0_CALIBRATION_FAILED = 32
    ADC1_CALIBRATION_FAILED = 64
    ADC0_CALIBRATION_TIMEOUT = 128
    ADC1_CALIBRATION_TIMEOUT = 256
    ADC0_READBACK_INVALID = 512
    ADC1_READBACK_INVALID = 1024


class AdcTriggerConfigurationFlag(IntFlag):
    NONE = 0
    CONFIGURED_STOPPED = 1
    CLOCKS_VALID = 2
    XBAR_ROUTES_VALID = 4
    QUEUES_VALID = 8
    ADC_HARDWARE_TRIGGER_VALID = 16
    ARM_SEQUENCE_EXERCISED = 32
    COMPLETION_TIMING_VALID = 64
    STOPPED_AFTER_DIAGNOSTIC = 128


class AdcTriggerError(IntFlag):
    NONE = 0
    CONVERTERS_NOT_READY = 1
    RESOURCE_BUSY = 2
    PERCLK_MISMATCH = 4
    IPG_CLOCK_MISMATCH = 8
    DWT_UNAVAILABLE = 16
    PIT_CONFIG_MISMATCH = 32
    XBAR_CONFIG_MISMATCH = 64
    ADC_ETC_CONFIG_MISMATCH = 128
    ADC_HARDWARE_TRIGGER_MISMATCH = 256
    ARM_FAILED = 512
    DIAGNOSTIC_TIMEOUT = 1024
    ADC_ETC_TRIGGER_ERROR = 2048
    COMPLETION_COUNT_MISMATCH = 4096
    COMPLETION_TIMING_OUT_OF_TOLERANCE = 8192
    CLEANUP_FAILED = 16384


class OutputBankMode(IntEnum):
    DISABLED = 0
    OUTPUT = 1


class OutputState(IntEnum):
    EMPTY = 0
    LOADING = 1
    COMMITTED = 2
    ARMED = 3
    RUNNING = 4
    HELD = 5
    FAULTED = 6


class OutputError(IntEnum):
    NONE = 0
    INVALID_SEGMENT = 1
    CAPACITY_EXCEEDED = 2
    CHECKSUM_MISMATCH = 3
    GENERATION_MISMATCH = 4
    INVALID_LIFECYCLE = 5
    TRUNCATED_UPLOAD = 6
    UNDERRUN = 7
    DMA_FAULT = 8
    RELEASE_FAILED = 9


BOOTSTRAP_CHECKSUM_ALGORITHM = ChecksumAlgorithm.ADLER32
DEFAULT_CHECKSUM_ALGORITHM = ChecksumAlgorithm.ADLER32
SUPPORTED_CHECKSUM_ALGORITHMS = frozenset(
    {
        ChecksumAlgorithm.ADLER32,
        ChecksumAlgorithm.CRC32C,
        ChecksumAlgorithm.CRC32_ISO_HDLC,
    }
)

SUPPORTED_CHECKSUM_MASK = 14
KNOWN_FRAME_FLAG_MASK = 32783
KNOWN_CAPABILITY_MASK = 2047
KNOWN_CONFIGURATION_PROFILE_MASK = 63
KNOWN_GPIO_CLOCK_ERROR_MASK = 32767
KNOWN_GPIO_CAPTURE_DIAGNOSTIC_FLAG_MASK = 511
KNOWN_GPIO_CAPTURE_ERROR_MASK = 65535
KNOWN_ADC_CONFIGURATION_FLAG_MASK = 511
KNOWN_ADC_INITIALIZATION_ERROR_MASK = 2047
KNOWN_ADC_TRIGGER_CONFIGURATION_FLAG_MASK = 255
KNOWN_ADC_TRIGGER_ERROR_MASK = 32767


FRAME_KIND_CLASS: dict[FrameKind, str] = {
    FrameKind.ADC_DATA: "data",
    FrameKind.GPIO_DATA: "data",
    FrameKind.INFO_REQUEST: "request",
    FrameKind.CONFIGURE_REQUEST: "request",
    FrameKind.START_REQUEST: "request",
    FrameKind.GET_STATUS_REQUEST: "request",
    FrameKind.STOP_REQUEST: "request",
    FrameKind.RESET_STATS_REQUEST: "request",
    FrameKind.PING_REQUEST: "request",
    FrameKind.CHECKSUM_BENCHMARK_REQUEST: "request",
    FrameKind.GPIO_CLOCK_DIAGNOSTIC_REQUEST: "request",
    FrameKind.GPIO_CAPTURE_DIAGNOSTIC_REQUEST: "request",
    FrameKind.INFO_RESPONSE: "response",
    FrameKind.CONFIGURE_RESPONSE: "response",
    FrameKind.START_RESPONSE: "response",
    FrameKind.GET_STATUS_RESPONSE: "response",
    FrameKind.STOP_RESPONSE: "response",
    FrameKind.RESET_STATS_RESPONSE: "response",
    FrameKind.PING_RESPONSE: "response",
    FrameKind.CHECKSUM_BENCHMARK_RESPONSE: "response",
    FrameKind.GPIO_CLOCK_DIAGNOSTIC_RESPONSE: "response",
    FrameKind.GPIO_CAPTURE_DIAGNOSTIC_RESPONSE: "response",
    FrameKind.OUTPUT_BEGIN_REQUEST: "request",
    FrameKind.OUTPUT_BEGIN_RESPONSE: "response",
    FrameKind.OUTPUT_APPEND_REQUEST: "request",
    FrameKind.OUTPUT_APPEND_RESPONSE: "response",
    FrameKind.OUTPUT_COMMIT_REQUEST: "request",
    FrameKind.OUTPUT_COMMIT_RESPONSE: "response",
    FrameKind.OUTPUT_ARM_REQUEST: "request",
    FrameKind.OUTPUT_ARM_RESPONSE: "response",
    FrameKind.OUTPUT_STATUS_REQUEST: "request",
    FrameKind.OUTPUT_STATUS_RESPONSE: "response",
    FrameKind.OUTPUT_CLEAR_REQUEST: "request",
    FrameKind.OUTPUT_CLEAR_RESPONSE: "response",
    FrameKind.ERROR_RESPONSE: "error_response",
}

ALLOWED_FLAGS_BY_KIND: dict[FrameKind, FrameFlag] = {
    FrameKind.ADC_DATA: FrameFlag.SYNTHETIC
    | FrameFlag.GAP_BEFORE
    | FrameFlag.EPOCH_START
    | FrameFlag.OVERRUN_BEFORE,
    FrameKind.GPIO_DATA: FrameFlag.SYNTHETIC
    | FrameFlag.GAP_BEFORE
    | FrameFlag.EPOCH_START
    | FrameFlag.OVERRUN_BEFORE,
    FrameKind.INFO_REQUEST: FrameFlag.NONE,
    FrameKind.CONFIGURE_REQUEST: FrameFlag.NONE,
    FrameKind.START_REQUEST: FrameFlag.NONE,
    FrameKind.GET_STATUS_REQUEST: FrameFlag.NONE,
    FrameKind.STOP_REQUEST: FrameFlag.NONE,
    FrameKind.RESET_STATS_REQUEST: FrameFlag.NONE,
    FrameKind.PING_REQUEST: FrameFlag.NONE,
    FrameKind.CHECKSUM_BENCHMARK_REQUEST: FrameFlag.NONE,
    FrameKind.GPIO_CLOCK_DIAGNOSTIC_REQUEST: FrameFlag.NONE,
    FrameKind.GPIO_CAPTURE_DIAGNOSTIC_REQUEST: FrameFlag.NONE,
    FrameKind.INFO_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.CONFIGURE_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.START_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.GET_STATUS_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.STOP_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.RESET_STATS_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.PING_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.CHECKSUM_BENCHMARK_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.GPIO_CLOCK_DIAGNOSTIC_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.GPIO_CAPTURE_DIAGNOSTIC_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.OUTPUT_BEGIN_REQUEST: FrameFlag.NONE,
    FrameKind.OUTPUT_BEGIN_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.OUTPUT_APPEND_REQUEST: FrameFlag.NONE,
    FrameKind.OUTPUT_APPEND_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.OUTPUT_COMMIT_REQUEST: FrameFlag.NONE,
    FrameKind.OUTPUT_COMMIT_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.OUTPUT_ARM_REQUEST: FrameFlag.NONE,
    FrameKind.OUTPUT_ARM_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.OUTPUT_STATUS_REQUEST: FrameFlag.NONE,
    FrameKind.OUTPUT_STATUS_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.OUTPUT_CLEAR_REQUEST: FrameFlag.NONE,
    FrameKind.OUTPUT_CLEAR_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.ERROR_RESPONSE: FrameFlag.RESPONSE_ERROR,
}

REQUEST_RESPONSE_KIND: dict[FrameKind, FrameKind] = {
    FrameKind.INFO_REQUEST: FrameKind.INFO_RESPONSE,
    FrameKind.CONFIGURE_REQUEST: FrameKind.CONFIGURE_RESPONSE,
    FrameKind.START_REQUEST: FrameKind.START_RESPONSE,
    FrameKind.GET_STATUS_REQUEST: FrameKind.GET_STATUS_RESPONSE,
    FrameKind.STOP_REQUEST: FrameKind.STOP_RESPONSE,
    FrameKind.RESET_STATS_REQUEST: FrameKind.RESET_STATS_RESPONSE,
    FrameKind.PING_REQUEST: FrameKind.PING_RESPONSE,
    FrameKind.CHECKSUM_BENCHMARK_REQUEST: FrameKind.CHECKSUM_BENCHMARK_RESPONSE,
    FrameKind.GPIO_CLOCK_DIAGNOSTIC_REQUEST: FrameKind.GPIO_CLOCK_DIAGNOSTIC_RESPONSE,
    FrameKind.GPIO_CAPTURE_DIAGNOSTIC_REQUEST: FrameKind.GPIO_CAPTURE_DIAGNOSTIC_RESPONSE,
    FrameKind.OUTPUT_BEGIN_REQUEST: FrameKind.OUTPUT_BEGIN_RESPONSE,
    FrameKind.OUTPUT_APPEND_REQUEST: FrameKind.OUTPUT_APPEND_RESPONSE,
    FrameKind.OUTPUT_COMMIT_REQUEST: FrameKind.OUTPUT_COMMIT_RESPONSE,
    FrameKind.OUTPUT_ARM_REQUEST: FrameKind.OUTPUT_ARM_RESPONSE,
    FrameKind.OUTPUT_STATUS_REQUEST: FrameKind.OUTPUT_STATUS_RESPONSE,
    FrameKind.OUTPUT_CLEAR_REQUEST: FrameKind.OUTPUT_CLEAR_RESPONSE,
}

COMMAND_REQUEST_KIND: dict[CommandKind, FrameKind] = {
    CommandKind.INFO: FrameKind.INFO_REQUEST,
    CommandKind.CONFIGURE: FrameKind.CONFIGURE_REQUEST,
    CommandKind.START: FrameKind.START_REQUEST,
    CommandKind.GET_STATUS: FrameKind.GET_STATUS_REQUEST,
    CommandKind.STOP: FrameKind.STOP_REQUEST,
    CommandKind.RESET_STATS: FrameKind.RESET_STATS_REQUEST,
    CommandKind.PING: FrameKind.PING_REQUEST,
    CommandKind.CHECKSUM_BENCHMARK: FrameKind.CHECKSUM_BENCHMARK_REQUEST,
    CommandKind.GPIO_CLOCK_DIAGNOSTIC: FrameKind.GPIO_CLOCK_DIAGNOSTIC_REQUEST,
    CommandKind.GPIO_CAPTURE_DIAGNOSTIC: FrameKind.GPIO_CAPTURE_DIAGNOSTIC_REQUEST,
    CommandKind.OUTPUT_BEGIN: FrameKind.OUTPUT_BEGIN_REQUEST,
    CommandKind.OUTPUT_APPEND: FrameKind.OUTPUT_APPEND_REQUEST,
    CommandKind.OUTPUT_COMMIT: FrameKind.OUTPUT_COMMIT_REQUEST,
    CommandKind.OUTPUT_ARM: FrameKind.OUTPUT_ARM_REQUEST,
    CommandKind.OUTPUT_STATUS: FrameKind.OUTPUT_STATUS_REQUEST,
    CommandKind.OUTPUT_CLEAR: FrameKind.OUTPUT_CLEAR_REQUEST,
}

COMMAND_RESPONSE_KIND: dict[CommandKind, FrameKind] = {
    CommandKind.INFO: FrameKind.INFO_RESPONSE,
    CommandKind.CONFIGURE: FrameKind.CONFIGURE_RESPONSE,
    CommandKind.START: FrameKind.START_RESPONSE,
    CommandKind.GET_STATUS: FrameKind.GET_STATUS_RESPONSE,
    CommandKind.STOP: FrameKind.STOP_RESPONSE,
    CommandKind.RESET_STATS: FrameKind.RESET_STATS_RESPONSE,
    CommandKind.PING: FrameKind.PING_RESPONSE,
    CommandKind.CHECKSUM_BENCHMARK: FrameKind.CHECKSUM_BENCHMARK_RESPONSE,
    CommandKind.GPIO_CLOCK_DIAGNOSTIC: FrameKind.GPIO_CLOCK_DIAGNOSTIC_RESPONSE,
    CommandKind.GPIO_CAPTURE_DIAGNOSTIC: FrameKind.GPIO_CAPTURE_DIAGNOSTIC_RESPONSE,
    CommandKind.OUTPUT_BEGIN: FrameKind.OUTPUT_BEGIN_RESPONSE,
    CommandKind.OUTPUT_APPEND: FrameKind.OUTPUT_APPEND_RESPONSE,
    CommandKind.OUTPUT_COMMIT: FrameKind.OUTPUT_COMMIT_RESPONSE,
    CommandKind.OUTPUT_ARM: FrameKind.OUTPUT_ARM_RESPONSE,
    CommandKind.OUTPUT_STATUS: FrameKind.OUTPUT_STATUS_RESPONSE,
    CommandKind.OUTPUT_CLEAR: FrameKind.OUTPUT_CLEAR_RESPONSE,
}

COMMAND_BY_REQUEST_KIND: dict[FrameKind, CommandKind] = {
    FrameKind.INFO_REQUEST: CommandKind.INFO,
    FrameKind.CONFIGURE_REQUEST: CommandKind.CONFIGURE,
    FrameKind.START_REQUEST: CommandKind.START,
    FrameKind.GET_STATUS_REQUEST: CommandKind.GET_STATUS,
    FrameKind.STOP_REQUEST: CommandKind.STOP,
    FrameKind.RESET_STATS_REQUEST: CommandKind.RESET_STATS,
    FrameKind.PING_REQUEST: CommandKind.PING,
    FrameKind.CHECKSUM_BENCHMARK_REQUEST: CommandKind.CHECKSUM_BENCHMARK,
    FrameKind.GPIO_CLOCK_DIAGNOSTIC_REQUEST: CommandKind.GPIO_CLOCK_DIAGNOSTIC,
    FrameKind.GPIO_CAPTURE_DIAGNOSTIC_REQUEST: CommandKind.GPIO_CAPTURE_DIAGNOSTIC,
    FrameKind.OUTPUT_BEGIN_REQUEST: CommandKind.OUTPUT_BEGIN,
    FrameKind.OUTPUT_APPEND_REQUEST: CommandKind.OUTPUT_APPEND,
    FrameKind.OUTPUT_COMMIT_REQUEST: CommandKind.OUTPUT_COMMIT,
    FrameKind.OUTPUT_ARM_REQUEST: CommandKind.OUTPUT_ARM,
    FrameKind.OUTPUT_STATUS_REQUEST: CommandKind.OUTPUT_STATUS,
    FrameKind.OUTPUT_CLEAR_REQUEST: CommandKind.OUTPUT_CLEAR,
}

COMMAND_BY_RESPONSE_KIND: dict[FrameKind, CommandKind] = {
    FrameKind.INFO_RESPONSE: CommandKind.INFO,
    FrameKind.CONFIGURE_RESPONSE: CommandKind.CONFIGURE,
    FrameKind.START_RESPONSE: CommandKind.START,
    FrameKind.GET_STATUS_RESPONSE: CommandKind.GET_STATUS,
    FrameKind.STOP_RESPONSE: CommandKind.STOP,
    FrameKind.RESET_STATS_RESPONSE: CommandKind.RESET_STATS,
    FrameKind.PING_RESPONSE: CommandKind.PING,
    FrameKind.CHECKSUM_BENCHMARK_RESPONSE: CommandKind.CHECKSUM_BENCHMARK,
    FrameKind.GPIO_CLOCK_DIAGNOSTIC_RESPONSE: CommandKind.GPIO_CLOCK_DIAGNOSTIC,
    FrameKind.GPIO_CAPTURE_DIAGNOSTIC_RESPONSE: CommandKind.GPIO_CAPTURE_DIAGNOSTIC,
    FrameKind.OUTPUT_BEGIN_RESPONSE: CommandKind.OUTPUT_BEGIN,
    FrameKind.OUTPUT_APPEND_RESPONSE: CommandKind.OUTPUT_APPEND,
    FrameKind.OUTPUT_COMMIT_RESPONSE: CommandKind.OUTPUT_COMMIT,
    FrameKind.OUTPUT_ARM_RESPONSE: CommandKind.OUTPUT_ARM,
    FrameKind.OUTPUT_STATUS_RESPONSE: CommandKind.OUTPUT_STATUS,
    FrameKind.OUTPUT_CLEAR_RESPONSE: CommandKind.OUTPUT_CLEAR,
}

PAYLOAD_SCHEMA_BY_KIND: dict[FrameKind, str] = {
    FrameKind.ADC_DATA: "adc_data",
    FrameKind.GPIO_DATA: "gpio_data",
    FrameKind.INFO_REQUEST: "empty",
    FrameKind.CONFIGURE_REQUEST: "configure_request",
    FrameKind.START_REQUEST: "empty",
    FrameKind.GET_STATUS_REQUEST: "empty",
    FrameKind.STOP_REQUEST: "empty",
    FrameKind.RESET_STATS_REQUEST: "empty",
    FrameKind.PING_REQUEST: "ping_request",
    FrameKind.CHECKSUM_BENCHMARK_REQUEST: "checksum_benchmark_request",
    FrameKind.GPIO_CLOCK_DIAGNOSTIC_REQUEST: "gpio_clock_diagnostic_request",
    FrameKind.GPIO_CAPTURE_DIAGNOSTIC_REQUEST: "empty",
    FrameKind.INFO_RESPONSE: "info_response",
    FrameKind.CONFIGURE_RESPONSE: "configure_response",
    FrameKind.START_RESPONSE: "configure_response",
    FrameKind.GET_STATUS_RESPONSE: "status_response",
    FrameKind.STOP_RESPONSE: "stop_response",
    FrameKind.RESET_STATS_RESPONSE: "reset_stats_response",
    FrameKind.PING_RESPONSE: "ping_response",
    FrameKind.CHECKSUM_BENCHMARK_RESPONSE: "checksum_benchmark_response",
    FrameKind.GPIO_CLOCK_DIAGNOSTIC_RESPONSE: "gpio_clock_diagnostic_response",
    FrameKind.GPIO_CAPTURE_DIAGNOSTIC_RESPONSE: "gpio_capture_diagnostic_response",
    FrameKind.OUTPUT_BEGIN_REQUEST: "output_begin_request",
    FrameKind.OUTPUT_BEGIN_RESPONSE: "output_status_response",
    FrameKind.OUTPUT_APPEND_REQUEST: "output_append_request",
    FrameKind.OUTPUT_APPEND_RESPONSE: "output_append_response",
    FrameKind.OUTPUT_COMMIT_REQUEST: "output_commit_request",
    FrameKind.OUTPUT_COMMIT_RESPONSE: "output_status_response",
    FrameKind.OUTPUT_ARM_REQUEST: "empty",
    FrameKind.OUTPUT_ARM_RESPONSE: "output_status_response",
    FrameKind.OUTPUT_STATUS_REQUEST: "empty",
    FrameKind.OUTPUT_STATUS_RESPONSE: "output_status_response",
    FrameKind.OUTPUT_CLEAR_REQUEST: "empty",
    FrameKind.OUTPUT_CLEAR_RESPONSE: "output_status_response",
    FrameKind.ERROR_RESPONSE: "error_response",
}

ERROR_PAYLOAD_SCHEMA_BY_KIND: dict[FrameKind, str] = {
    FrameKind.INFO_RESPONSE: "response_prefix",
    FrameKind.CONFIGURE_RESPONSE: "response_prefix",
    FrameKind.START_RESPONSE: "response_prefix",
    FrameKind.GET_STATUS_RESPONSE: "response_prefix",
    FrameKind.STOP_RESPONSE: "response_prefix",
    FrameKind.RESET_STATS_RESPONSE: "response_prefix",
    FrameKind.PING_RESPONSE: "response_prefix",
    FrameKind.CHECKSUM_BENCHMARK_RESPONSE: "response_prefix",
    FrameKind.GPIO_CLOCK_DIAGNOSTIC_RESPONSE: "response_prefix",
    FrameKind.GPIO_CAPTURE_DIAGNOSTIC_RESPONSE: "response_prefix",
    FrameKind.OUTPUT_BEGIN_RESPONSE: "output_status_response",
    FrameKind.OUTPUT_APPEND_RESPONSE: "output_status_response",
    FrameKind.OUTPUT_COMMIT_RESPONSE: "output_status_response",
    FrameKind.OUTPUT_ARM_RESPONSE: "output_status_response",
    FrameKind.OUTPUT_STATUS_RESPONSE: "output_status_response",
    FrameKind.OUTPUT_CLEAR_RESPONSE: "output_status_response",
}

PAYLOAD_SIZE_BY_SCHEMA: dict[str, int] = {
    "empty": 0,
    "adc_data": 4048,
    "gpio_data": 4048,
    "configure_request": 8,
    "response_prefix": 4,
    "info_response": 412,
    "configure_response": 12,
    "status_response": 1228,
    "stop_response": 8,
    "reset_stats_response": 8,
    "ping_request": 8,
    "ping_response": 12,
    "checksum_benchmark_request": 8,
    "checksum_benchmark_response": 96,
    "gpio_clock_diagnostic_request": 8,
    "gpio_clock_diagnostic_response": 140,
    "gpio_capture_diagnostic_response": 144,
    "error_response": 8,
    "output_begin_request": 8,
    "output_append_request": 8,
    "output_commit_request": 8,
    "output_append_response": 16,
    "output_status_response": 224,
}

EMPTY_PAYLOAD_SIZE = 0
ADC_DATA_PAYLOAD_SIZE = 4048
ADC_DATA_PAIRS_OFFSET = 0
ADC_DATA_PAIRS_COUNT = 1012
GPIO_DATA_PAYLOAD_SIZE = 4048
GPIO_DATA_SAMPLES_OFFSET = 0
GPIO_DATA_SAMPLES_COUNT = 4048
CONFIGURE_REQUEST_PAYLOAD_SIZE = 8
CONFIGURE_REQUEST_STREAM_MASK_OFFSET = 0
CONFIGURE_REQUEST_SOURCE_OFFSET = 1
CONFIGURE_REQUEST_DATA_CHECKSUM_ALGORITHM_OFFSET = 2
CONFIGURE_REQUEST_RESERVED_OFFSET = 3
CONFIGURE_REQUEST_DATA_FRAME_BYTES_OFFSET = 4
RESPONSE_PREFIX_PAYLOAD_SIZE = 4
RESPONSE_PREFIX_RESPONSE_STATUS_OFFSET = 0
RESPONSE_PREFIX_RESERVED_OFFSET = 1
RESPONSE_PREFIX_ERROR_CODE_OFFSET = 2
INFO_RESPONSE_PAYLOAD_SIZE = 412
INFO_RESPONSE_RESPONSE_STATUS_OFFSET = 0
INFO_RESPONSE_RESERVED_0_OFFSET = 1
INFO_RESPONSE_ERROR_CODE_OFFSET = 2
INFO_RESPONSE_DEVICE_STATE_OFFSET = 4
INFO_RESPONSE_PROTOCOL_VERSION_OFFSET = 5
INFO_RESPONSE_SUPPORTED_STREAM_MASK_OFFSET = 6
INFO_RESPONSE_SUPPORTED_SOURCE_MASK_OFFSET = 7
INFO_RESPONSE_SUPPORTED_CHECKSUM_MASK_OFFSET = 8
INFO_RESPONSE_CAPABILITY_BITS_OFFSET = 12
INFO_RESPONSE_TIMESTAMP_HZ_OFFSET = 16
INFO_RESPONSE_DATA_FRAME_BYTES_OFFSET = 20
INFO_RESPONSE_MAX_CONTROL_FRAME_BYTES_OFFSET = 24
INFO_RESPONSE_ADC_PAIR_RATE_HZ_OFFSET = 28
INFO_RESPONSE_GPIO_SAMPLE_RATE_HZ_OFFSET = 32
INFO_RESPONSE_ADC_PAIR_PERIOD_TICKS_OFFSET = 36
INFO_RESPONSE_ADC1_PHASE_TICKS_OFFSET = 38
INFO_RESPONSE_GPIO_SAMPLE_PERIOD_TICKS_OFFSET = 40
INFO_RESPONSE_ADC_RESOLUTION_BITS_OFFSET = 42
INFO_RESPONSE_ADC_CONTAINER_BYTES_OFFSET = 43
INFO_RESPONSE_GPIO_PIN_COUNT_OFFSET = 44
INFO_RESPONSE_DATA_CHECKSUM_ALGORITHM_OFFSET = 45
INFO_RESPONSE_GPIO_PIN_MAP_OFFSET = 46
INFO_RESPONSE_GPIO_PIN_MAP_COUNT = 8
INFO_RESPONSE_HARDWARE_SERIAL_OFFSET = 54
INFO_RESPONSE_FIRMWARE_VERSION_MAJOR_OFFSET = 58
INFO_RESPONSE_FIRMWARE_VERSION_MINOR_OFFSET = 59
INFO_RESPONSE_FIRMWARE_VERSION_PATCH_OFFSET = 60
INFO_RESPONSE_RESERVED_2_OFFSET = 61
INFO_RESPONSE_BOARD_ID_OFFSET = 62
INFO_RESPONSE_MCU_ID_OFFSET = 64
INFO_RESPONSE_BUILD_ID_OFFSET = 66
INFO_RESPONSE_BUILD_ID_COUNT = 32
INFO_RESPONSE_GPIO_PACKED_WIDTH_BITS_OFFSET = 98
INFO_RESPONSE_GPIO_RAW_RING_DEPTH_OFFSET = 99
INFO_RESPONSE_GPIO_PACKED_RING_DEPTH_OFFSET = 100
INFO_RESPONSE_GPIO_CAPTURE_DIAGNOSTIC_MODE_OFFSET = 101
INFO_RESPONSE_GPIO_CAPTURE_DIAGNOSTIC_FLAGS_OFFSET = 102
INFO_RESPONSE_GPIO_RAW_SAMPLES_PER_BUFFER_OFFSET = 104
INFO_RESPONSE_GPIO_RAW_RING_BYTES_OFFSET = 108
INFO_RESPONSE_GPIO_PACKED_RING_BYTES_OFFSET = 112
INFO_RESPONSE_GPIO_PACKET_BUFFER_COUNT_OFFSET = 116
INFO_RESPONSE_RESERVED_3_OFFSET = 118
INFO_RESPONSE_GPIO_PIT_CHANNEL_OFFSET = 120
INFO_RESPONSE_GPIO_XBAR_INPUT_OFFSET = 121
INFO_RESPONSE_GPIO_XBAR_OUTPUT_OFFSET = 122
INFO_RESPONSE_GPIO_EDMA_CHANNEL_OFFSET = 123
INFO_RESPONSE_GPIO_DMAMUX_SOURCE_OFFSET = 124
INFO_RESPONSE_GPIO_EDMA_PRIORITY_OFFSET = 125
INFO_RESPONSE_GPIO_XBAR_ACTIVE_EDGE_OFFSET = 126
INFO_RESPONSE_RESERVED_4_OFFSET = 127
INFO_RESPONSE_ADC_CODE_MIN_OFFSET = 128
INFO_RESPONSE_ADC_CODE_MAX_OFFSET = 130
INFO_RESPONSE_ADC_REFERENCE_OFFSET = 132
INFO_RESPONSE_ADC_CLOCK_SOURCE_OFFSET = 133
INFO_RESPONSE_ADC_CLOCK_DIVIDER_OFFSET = 134
INFO_RESPONSE_ADC_HARDWARE_AVERAGE_COUNT_OFFSET = 135
INFO_RESPONSE_ADC_REFERENCE_MV_NOMINAL_OFFSET = 136
INFO_RESPONSE_ADC_INPUT_MIN_MV_NOMINAL_OFFSET = 138
INFO_RESPONSE_ADC_INPUT_MAX_MV_NOMINAL_OFFSET = 140
INFO_RESPONSE_ADC_SAMPLE_TIME_ADCK_OFFSET = 142
INFO_RESPONSE_ADC_CONVERSION_MODE_OFFSET = 143
INFO_RESPONSE_ADC_CONFIGURATION_FLAGS_OFFSET = 144
INFO_RESPONSE_ADC0_CALIBRATION_STATE_OFFSET = 146
INFO_RESPONSE_ADC1_CALIBRATION_STATE_OFFSET = 147
INFO_RESPONSE_ADC0_PIN_OFFSET = 148
INFO_RESPONSE_ADC1_PIN_OFFSET = 149
INFO_RESPONSE_ADC0_PERIPHERAL_OFFSET = 150
INFO_RESPONSE_ADC1_PERIPHERAL_OFFSET = 151
INFO_RESPONSE_ADC0_CHANNEL_OFFSET = 152
INFO_RESPONSE_ADC1_CHANNEL_OFFSET = 153
INFO_RESPONSE_RESERVED_5_OFFSET = 154
INFO_RESPONSE_ADC_IPG_CLOCK_HZ_OFFSET = 156
INFO_RESPONSE_ADC_CLOCK_HZ_OFFSET = 160
INFO_RESPONSE_ADC_CALIBRATION_DEADLINE_US_OFFSET = 164
INFO_RESPONSE_ADC0_CALIBRATION_CYCLES_OFFSET = 168
INFO_RESPONSE_ADC1_CALIBRATION_CYCLES_OFFSET = 172
INFO_RESPONSE_ADC_INITIALIZATION_ERROR_FLAGS_OFFSET = 176
INFO_RESPONSE_ADC_TRIGGER_CONFIGURATION_FLAGS_OFFSET = 180
INFO_RESPONSE_RESERVED_6_OFFSET = 182
INFO_RESPONSE_ADC_TRIGGER_ERROR_FLAGS_OFFSET = 184
INFO_RESPONSE_ADC_TRIGGER_PIT_CLOCK_HZ_OFFSET = 188
INFO_RESPONSE_ADC_TRIGGER_DWT_CLOCK_HZ_OFFSET = 192
INFO_RESPONSE_ADC_TRIGGER_GPIO_MASTER_RATE_HZ_OFFSET = 196
INFO_RESPONSE_ADC_TRIGGER_PAIR_RATE_HZ_OFFSET = 200
INFO_RESPONSE_ADC_TRIGGER_IPG_CLOCK_HZ_OFFSET = 204
INFO_RESPONSE_ADC_TRIGGER_GPIO_MASTER_PIT_CHANNEL_OFFSET = 208
INFO_RESPONSE_ADC_TRIGGER_PAIR_PIT_CHANNEL_OFFSET = 209
INFO_RESPONSE_ADC_TRIGGER_GPIO_MASTER_PIT_LOAD_OFFSET = 210
INFO_RESPONSE_ADC_TRIGGER_PAIR_PIT_LOAD_OFFSET = 211
INFO_RESPONSE_ADC_TRIGGER_PREDIVIDER_OFFSET = 212
INFO_RESPONSE_ADC_TRIGGER_CHAIN_LENGTH_OFFSET = 213
INFO_RESPONSE_ADC0_TRIGGER_XBAR_INPUT_OFFSET = 214
INFO_RESPONSE_ADC1_TRIGGER_XBAR_INPUT_OFFSET = 215
INFO_RESPONSE_ADC0_TRIGGER_XBAR_OUTPUT_OFFSET = 216
INFO_RESPONSE_ADC1_TRIGGER_XBAR_OUTPUT_OFFSET = 217
INFO_RESPONSE_ADC0_ETC_TRIGGER_QUEUE_OFFSET = 218
INFO_RESPONSE_ADC1_ETC_TRIGGER_QUEUE_OFFSET = 219
INFO_RESPONSE_ADC0_TRIGGER_INITIAL_DELAY_OFFSET = 220
INFO_RESPONSE_ADC1_TRIGGER_INITIAL_DELAY_OFFSET = 222
INFO_RESPONSE_ADC0_TRIGGER_EFFECTIVE_DELAY_OFFSET = 224
INFO_RESPONSE_ADC1_TRIGGER_EFFECTIVE_DELAY_OFFSET = 226
INFO_RESPONSE_ADC_TRIGGER_PHASE_IPG_CYCLES_OFFSET = 228
INFO_RESPONSE_RESERVED_7_OFFSET = 230
INFO_RESPONSE_ADC_TRIGGER_CCM_CSCMR1_CONFIGURED_OFFSET = 232
INFO_RESPONSE_ADC_TRIGGER_CCM_CCGR1_CONFIGURED_OFFSET = 236
INFO_RESPONSE_ADC_TRIGGER_CCM_CCGR2_CONFIGURED_OFFSET = 240
INFO_RESPONSE_ADC_TRIGGER_PIT_MCR_CONFIGURED_OFFSET = 244
INFO_RESPONSE_ADC_TRIGGER_GPIO_MASTER_TCTRL_CONFIGURED_OFFSET = 248
INFO_RESPONSE_ADC_TRIGGER_PAIR_TCTRL_CONFIGURED_OFFSET = 252
INFO_RESPONSE_ADC_ETC_CTRL_CONFIGURED_OFFSET = 256
INFO_RESPONSE_ADC0_ETC_TRIGGER_CTRL_CONFIGURED_OFFSET = 260
INFO_RESPONSE_ADC1_ETC_TRIGGER_CTRL_CONFIGURED_OFFSET = 264
INFO_RESPONSE_ADC0_ETC_TRIGGER_COUNTER_CONFIGURED_OFFSET = 268
INFO_RESPONSE_ADC1_ETC_TRIGGER_COUNTER_CONFIGURED_OFFSET = 272
INFO_RESPONSE_ADC0_ETC_CHAIN_CONFIGURED_OFFSET = 276
INFO_RESPONSE_ADC1_ETC_CHAIN_CONFIGURED_OFFSET = 280
INFO_RESPONSE_ADC_ETC_DONE0_1_IRQ_FINAL_OFFSET = 284
INFO_RESPONSE_ADC_ETC_DONE2_ERR_IRQ_FINAL_OFFSET = 288
INFO_RESPONSE_ADC0_COMPLETION_COUNT_OFFSET = 292
INFO_RESPONSE_ADC1_COMPLETION_COUNT_OFFSET = 296
INFO_RESPONSE_ADC_COMPLETION_DELTA_CYCLES_OFFSET = 300
INFO_RESPONSE_ADC_COMPLETION_EXPECTED_DELTA_CYCLES_OFFSET = 304
INFO_RESPONSE_ADC_COMPLETION_TOLERANCE_CYCLES_OFFSET = 308
INFO_RESPONSE_ADC_COMPLETION_DIAGNOSTIC_ELAPSED_CYCLES_OFFSET = 312
INFO_RESPONSE_ADC_TRIGGER_ERROR_COUNT_OFFSET = 316
INFO_RESPONSE_ADC0_TRIGGER_XBAR_SEL_CONFIGURED_OFFSET = 320
INFO_RESPONSE_ADC1_TRIGGER_XBAR_SEL_CONFIGURED_OFFSET = 322
INFO_RESPONSE_APPLIED_STREAM_MASK_OFFSET = 324
INFO_RESPONSE_APPLIED_SOURCE_OFFSET = 325
INFO_RESPONSE_SUPPORTED_CONFIGURATION_MASK_OFFSET = 326
INFO_RESPONSE_DATA_PAYLOAD_BYTES_OFFSET = 328
INFO_RESPONSE_ADC_PAIRS_PER_FRAME_OFFSET = 330
INFO_RESPONSE_GPIO_SAMPLES_PER_FRAME_OFFSET = 332
INFO_RESPONSE_RESERVED_8_OFFSET = 334
INFO_RESPONSE_FRAME_COVERAGE_TICKS_OFFSET = 336
INFO_RESPONSE_ADC_DMA_RING_DEPTH_OFFSET = 340
INFO_RESPONSE_ADC_PAIR_BYTES_OFFSET = 341
INFO_RESPONSE_ADC_EDMA_CHANNELS_OFFSET = 342
INFO_RESPONSE_ADC_EDMA_CHANNELS_COUNT = 2
INFO_RESPONSE_ADC_EDMA_PRIORITIES_OFFSET = 344
INFO_RESPONSE_ADC_EDMA_PRIORITIES_COUNT = 2
INFO_RESPONSE_ADC_DMAMUX_SOURCES_OFFSET = 346
INFO_RESPONSE_ADC_DMAMUX_SOURCES_COUNT = 2
INFO_RESPONSE_ADC_DMA_IRQ_PRIORITY_OFFSET = 348
INFO_RESPONSE_GPIO_DMA_IRQ_PRIORITY_OFFSET = 349
INFO_RESPONSE_ADC_PAIRS_PER_BUFFER_OFFSET = 350
INFO_RESPONSE_ADC_DMA_RING_BYTES_OFFSET = 352
INFO_RESPONSE_PACKET_BUFFER_COUNT_OFFSET = 356
INFO_RESPONSE_PACKET_PRIMARY_COUNT_OFFSET = 358
INFO_RESPONSE_PACKET_RESERVE_COUNT_OFFSET = 360
INFO_RESPONSE_PACKET_READY_QUEUE_CAPACITY_OFFSET = 362
INFO_RESPONSE_PACKET_TRANSMIT_QUEUE_CAPACITY_OFFSET = 364
INFO_RESPONSE_COMMAND_QUEUE_CAPACITY_OFFSET = 366
INFO_RESPONSE_RESPONSE_QUEUE_CAPACITY_OFFSET = 367
INFO_RESPONSE_NOMINAL_PAYLOAD_BYTES_PER_SECOND_PER_STREAM_OFFSET = 368
INFO_RESPONSE_NOMINAL_FRAMED_BYTES_PER_SECOND_PER_STREAM_OFFSET = 372
INFO_RESPONSE_OUTPUT_BANK_MODE_OFFSET = 376
INFO_RESPONSE_OUTPUT_PIN_COUNT_OFFSET = 377
INFO_RESPONSE_OUTPUT_STATE_WIDTH_BITS_OFFSET = 378
INFO_RESPONSE_OUTPUT_DURATION_QUANTUM_US_OFFSET = 379
INFO_RESPONSE_OUTPUT_PIN_MAP_OFFSET = 380
INFO_RESPONSE_OUTPUT_PIN_MAP_COUNT = 8
INFO_RESPONSE_OUTPUT_GPIO_BITS_BY_LOGICAL_BIT_OFFSET = 388
INFO_RESPONSE_OUTPUT_GPIO_BITS_BY_LOGICAL_BIT_COUNT = 8
INFO_RESPONSE_OUTPUT_RATE_HZ_OFFSET = 396
INFO_RESPONSE_OUTPUT_PERIOD_TICKS_OFFSET = 400
INFO_RESPONSE_OUTPUT_CAPACITY_SEGMENTS_OFFSET = 404
INFO_RESPONSE_OUTPUT_LEGAL_STATE_MASK_OFFSET = 408
CONFIGURE_RESPONSE_PAYLOAD_SIZE = 12
CONFIGURE_RESPONSE_RESPONSE_STATUS_OFFSET = 0
CONFIGURE_RESPONSE_RESERVED_0_OFFSET = 1
CONFIGURE_RESPONSE_ERROR_CODE_OFFSET = 2
CONFIGURE_RESPONSE_STREAM_MASK_OFFSET = 4
CONFIGURE_RESPONSE_SOURCE_OFFSET = 5
CONFIGURE_RESPONSE_DATA_CHECKSUM_ALGORITHM_OFFSET = 6
CONFIGURE_RESPONSE_RESERVED_1_OFFSET = 7
CONFIGURE_RESPONSE_DATA_FRAME_BYTES_OFFSET = 8
STATUS_RESPONSE_PAYLOAD_SIZE = 1228
STATUS_RESPONSE_RESPONSE_STATUS_OFFSET = 0
STATUS_RESPONSE_RESERVED_OFFSET = 1
STATUS_RESPONSE_ERROR_CODE_OFFSET = 2
STATUS_RESPONSE_DEVICE_STATE_OFFSET = 4
STATUS_RESPONSE_STREAM_MASK_OFFSET = 5
STATUS_RESPONSE_SOURCE_OFFSET = 6
STATUS_RESPONSE_DATA_CHECKSUM_ALGORITHM_OFFSET = 7
STATUS_RESPONSE_DATA_FRAME_BYTES_OFFSET = 8
STATUS_RESPONSE_ADC_FRAMES_EMITTED_OFFSET = 12
STATUS_RESPONSE_GPIO_FRAMES_EMITTED_OFFSET = 20
STATUS_RESPONSE_ADC_ITEMS_DROPPED_OFFSET = 28
STATUS_RESPONSE_GPIO_ITEMS_DROPPED_OFFSET = 36
STATUS_RESPONSE_PARSER_ERRORS_OFFSET = 44
STATUS_RESPONSE_TRANSPORT_ERRORS_OFFSET = 48
STATUS_RESPONSE_STATS_GENERATION_OFFSET = 52
STATUS_RESPONSE_GPIO_SAMPLES_CAPTURED_OFFSET = 56
STATUS_RESPONSE_GPIO_SAMPLES_PACKED_OFFSET = 64
STATUS_RESPONSE_GPIO_SAMPLES_FRAMED_OFFSET = 72
STATUS_RESPONSE_GPIO_SAMPLES_TRANSMITTED_OFFSET = 80
STATUS_RESPONSE_GPIO_RAW_SAMPLES_LOST_OFFSET = 88
STATUS_RESPONSE_GPIO_PACKER_SAMPLES_DROPPED_OFFSET = 96
STATUS_RESPONSE_GPIO_RAW_RING_OVERRUNS_OFFSET = 104
STATUS_RESPONSE_GPIO_DMA_MAJOR_LOOPS_OFFSET = 112
STATUS_RESPONSE_GPIO_RAW_READY_DEPTH_OFFSET = 120
STATUS_RESPONSE_GPIO_RAW_READY_HIGH_WATER_OFFSET = 122
STATUS_RESPONSE_GPIO_PACKED_READY_DEPTH_OFFSET = 124
STATUS_RESPONSE_GPIO_PACKED_READY_HIGH_WATER_OFFSET = 126
STATUS_RESPONSE_PACKET_READY_DEPTH_OFFSET = 128
STATUS_RESPONSE_PACKET_TRANSMIT_DEPTH_OFFSET = 130
STATUS_RESPONSE_PACKET_OWNED_HIGH_WATER_OFFSET = 132
STATUS_RESPONSE_GPIO_PROCESSING_CPU_BASIS_POINTS_OFFSET = 134
STATUS_RESPONSE_GPIO_HARDWARE_ERRORS_OFFSET = 136
STATUS_RESPONSE_GPIO_RAW_INVARIANT_ERRORS_OFFSET = 140
STATUS_RESPONSE_GPIO_PACKER_SOURCE_ERRORS_OFFSET = 144
STATUS_RESPONSE_GPIO_PACKER_PIPELINE_ERRORS_OFFSET = 148
STATUS_RESPONSE_GPIO_PACKER_CHRONOLOGY_ERRORS_OFFSET = 152
STATUS_RESPONSE_GPIO_RESOURCE_CONFLICTS_OFFSET = 156
STATUS_RESPONSE_GPIO_START_ERRORS_OFFSET = 160
STATUS_RESPONSE_GPIO_STOP_ERRORS_OFFSET = 164
STATUS_RESPONSE_GPIO_STALE_DMA_COMPLETIONS_OFFSET = 168
STATUS_RESPONSE_ADC_RESOLUTION_BITS_OFFSET = 172
STATUS_RESPONSE_ADC_CONTAINER_BYTES_OFFSET = 173
STATUS_RESPONSE_ADC0_CALIBRATION_STATE_OFFSET = 174
STATUS_RESPONSE_ADC1_CALIBRATION_STATE_OFFSET = 175
STATUS_RESPONSE_ADC_CODE_MIN_OFFSET = 176
STATUS_RESPONSE_ADC_CODE_MAX_OFFSET = 178
STATUS_RESPONSE_ADC_REFERENCE_OFFSET = 180
STATUS_RESPONSE_ADC_CLOCK_SOURCE_OFFSET = 181
STATUS_RESPONSE_ADC_CLOCK_DIVIDER_OFFSET = 182
STATUS_RESPONSE_ADC_HARDWARE_AVERAGE_COUNT_OFFSET = 183
STATUS_RESPONSE_ADC_REFERENCE_MV_NOMINAL_OFFSET = 184
STATUS_RESPONSE_ADC_INPUT_MIN_MV_NOMINAL_OFFSET = 186
STATUS_RESPONSE_ADC_INPUT_MAX_MV_NOMINAL_OFFSET = 188
STATUS_RESPONSE_ADC_SAMPLE_TIME_ADCK_OFFSET = 190
STATUS_RESPONSE_ADC_CONVERSION_MODE_OFFSET = 191
STATUS_RESPONSE_ADC_CONFIGURATION_FLAGS_OFFSET = 192
STATUS_RESPONSE_ADC0_PIN_OFFSET = 194
STATUS_RESPONSE_ADC1_PIN_OFFSET = 195
STATUS_RESPONSE_ADC0_PERIPHERAL_OFFSET = 196
STATUS_RESPONSE_ADC1_PERIPHERAL_OFFSET = 197
STATUS_RESPONSE_ADC0_CHANNEL_OFFSET = 198
STATUS_RESPONSE_ADC1_CHANNEL_OFFSET = 199
STATUS_RESPONSE_ADC_IPG_CLOCK_HZ_OFFSET = 200
STATUS_RESPONSE_ADC_CLOCK_HZ_OFFSET = 204
STATUS_RESPONSE_ADC_CALIBRATION_DEADLINE_US_OFFSET = 208
STATUS_RESPONSE_ADC0_CALIBRATION_CYCLES_OFFSET = 212
STATUS_RESPONSE_ADC1_CALIBRATION_CYCLES_OFFSET = 216
STATUS_RESPONSE_ADC_INITIALIZATION_ERROR_FLAGS_OFFSET = 220
STATUS_RESPONSE_ADC_TRIGGER_CONFIGURATION_FLAGS_OFFSET = 224
STATUS_RESPONSE_RESERVED_2_OFFSET = 226
STATUS_RESPONSE_ADC_TRIGGER_ERROR_FLAGS_OFFSET = 228
STATUS_RESPONSE_ADC_TRIGGER_PIT_CLOCK_HZ_OFFSET = 232
STATUS_RESPONSE_ADC_TRIGGER_DWT_CLOCK_HZ_OFFSET = 236
STATUS_RESPONSE_ADC_TRIGGER_GPIO_MASTER_RATE_HZ_OFFSET = 240
STATUS_RESPONSE_ADC_TRIGGER_PAIR_RATE_HZ_OFFSET = 244
STATUS_RESPONSE_ADC_TRIGGER_IPG_CLOCK_HZ_OFFSET = 248
STATUS_RESPONSE_ADC_TRIGGER_GPIO_MASTER_PIT_CHANNEL_OFFSET = 252
STATUS_RESPONSE_ADC_TRIGGER_PAIR_PIT_CHANNEL_OFFSET = 253
STATUS_RESPONSE_ADC_TRIGGER_GPIO_MASTER_PIT_LOAD_OFFSET = 254
STATUS_RESPONSE_ADC_TRIGGER_PAIR_PIT_LOAD_OFFSET = 255
STATUS_RESPONSE_ADC_TRIGGER_PREDIVIDER_OFFSET = 256
STATUS_RESPONSE_ADC_TRIGGER_CHAIN_LENGTH_OFFSET = 257
STATUS_RESPONSE_ADC0_TRIGGER_XBAR_INPUT_OFFSET = 258
STATUS_RESPONSE_ADC1_TRIGGER_XBAR_INPUT_OFFSET = 259
STATUS_RESPONSE_ADC0_TRIGGER_XBAR_OUTPUT_OFFSET = 260
STATUS_RESPONSE_ADC1_TRIGGER_XBAR_OUTPUT_OFFSET = 261
STATUS_RESPONSE_ADC0_ETC_TRIGGER_QUEUE_OFFSET = 262
STATUS_RESPONSE_ADC1_ETC_TRIGGER_QUEUE_OFFSET = 263
STATUS_RESPONSE_ADC0_TRIGGER_INITIAL_DELAY_OFFSET = 264
STATUS_RESPONSE_ADC1_TRIGGER_INITIAL_DELAY_OFFSET = 266
STATUS_RESPONSE_ADC0_TRIGGER_EFFECTIVE_DELAY_OFFSET = 268
STATUS_RESPONSE_ADC1_TRIGGER_EFFECTIVE_DELAY_OFFSET = 270
STATUS_RESPONSE_ADC_TRIGGER_PHASE_IPG_CYCLES_OFFSET = 272
STATUS_RESPONSE_RESERVED_3_OFFSET = 274
STATUS_RESPONSE_ADC_TRIGGER_CCM_CSCMR1_CONFIGURED_OFFSET = 276
STATUS_RESPONSE_ADC_TRIGGER_CCM_CCGR1_CONFIGURED_OFFSET = 280
STATUS_RESPONSE_ADC_TRIGGER_CCM_CCGR2_CONFIGURED_OFFSET = 284
STATUS_RESPONSE_ADC_TRIGGER_PIT_MCR_CONFIGURED_OFFSET = 288
STATUS_RESPONSE_ADC_TRIGGER_GPIO_MASTER_TCTRL_CONFIGURED_OFFSET = 292
STATUS_RESPONSE_ADC_TRIGGER_PAIR_TCTRL_CONFIGURED_OFFSET = 296
STATUS_RESPONSE_ADC_ETC_CTRL_CONFIGURED_OFFSET = 300
STATUS_RESPONSE_ADC0_ETC_TRIGGER_CTRL_CONFIGURED_OFFSET = 304
STATUS_RESPONSE_ADC1_ETC_TRIGGER_CTRL_CONFIGURED_OFFSET = 308
STATUS_RESPONSE_ADC0_ETC_TRIGGER_COUNTER_CONFIGURED_OFFSET = 312
STATUS_RESPONSE_ADC1_ETC_TRIGGER_COUNTER_CONFIGURED_OFFSET = 316
STATUS_RESPONSE_ADC0_ETC_CHAIN_CONFIGURED_OFFSET = 320
STATUS_RESPONSE_ADC1_ETC_CHAIN_CONFIGURED_OFFSET = 324
STATUS_RESPONSE_ADC_ETC_DONE0_1_IRQ_FINAL_OFFSET = 328
STATUS_RESPONSE_ADC_ETC_DONE2_ERR_IRQ_FINAL_OFFSET = 332
STATUS_RESPONSE_ADC0_COMPLETION_COUNT_OFFSET = 336
STATUS_RESPONSE_ADC1_COMPLETION_COUNT_OFFSET = 340
STATUS_RESPONSE_ADC_COMPLETION_DELTA_CYCLES_OFFSET = 344
STATUS_RESPONSE_ADC_COMPLETION_EXPECTED_DELTA_CYCLES_OFFSET = 348
STATUS_RESPONSE_ADC_COMPLETION_TOLERANCE_CYCLES_OFFSET = 352
STATUS_RESPONSE_ADC_COMPLETION_DIAGNOSTIC_ELAPSED_CYCLES_OFFSET = 356
STATUS_RESPONSE_ADC_TRIGGER_ERROR_COUNT_OFFSET = 360
STATUS_RESPONSE_ADC0_TRIGGER_XBAR_SEL_CONFIGURED_OFFSET = 364
STATUS_RESPONSE_ADC1_TRIGGER_XBAR_SEL_CONFIGURED_OFFSET = 366
STATUS_RESPONSE_ADC0_DMA_MAJOR_LOOPS_OFFSET = 368
STATUS_RESPONSE_ADC1_DMA_MAJOR_LOOPS_OFFSET = 376
STATUS_RESPONSE_ADC0_DMA_RESULTS_OFFSET = 384
STATUS_RESPONSE_ADC1_DMA_RESULTS_OFFSET = 392
STATUS_RESPONSE_ADC_PAIRED_MAJOR_LOOPS_OFFSET = 400
STATUS_RESPONSE_ADC_BUFFERS_COMPLETED_OFFSET = 408
STATUS_RESPONSE_ADC_BUFFERS_ACQUIRED_OFFSET = 416
STATUS_RESPONSE_ADC_BUFFERS_RELEASED_OFFSET = 424
STATUS_RESPONSE_ADC_PAIRS_CAPTURED_OFFSET = 432
STATUS_RESPONSE_ADC_PAIRS_DELIVERED_OFFSET = 440
STATUS_RESPONSE_ADC_PAIRS_FRAMED_OFFSET = 448
STATUS_RESPONSE_ADC_PAIRS_TRANSMITTED_OFFSET = 456
STATUS_RESPONSE_ADC_RAW_PAIRS_LOST_OFFSET = 464
STATUS_RESPONSE_ADC_STOP_PAIRS_DISCARDED_OFFSET = 472
STATUS_RESPONSE_ADC_INCOMPLETE_CONVERSIONS_OFFSET = 480
STATUS_RESPONSE_ADC_OVERWRITTEN_CONVERSIONS_OFFSET = 488
STATUS_RESPONSE_ADC_RAW_RING_OVERRUNS_OFFSET = 496
STATUS_RESPONSE_ADC_INCOMPLETE_BUFFERS_OFFSET = 504
STATUS_RESPONSE_ADC_RAW_READY_DEPTH_OFFSET = 512
STATUS_RESPONSE_ADC_RAW_READY_HIGH_WATER_OFFSET = 514
STATUS_RESPONSE_ADC_ETC_ERROR_EVENTS_OFFSET = 516
STATUS_RESPONSE_ADC_ETC_ERROR_FLAGS_OFFSET = 520
STATUS_RESPONSE_ADC_DMA_ERROR_EVENTS_OFFSET = 524
STATUS_RESPONSE_ADC_COMPLETION_MISMATCHES_OFFSET = 528
STATUS_RESPONSE_ADC_DESTINATION_MISMATCHES_OFFSET = 532
STATUS_RESPONSE_ADC_SCHEDULE_EXHAUSTIONS_OFFSET = 536
STATUS_RESPONSE_ADC_RAW_INVARIANT_ERRORS_OFFSET = 540
STATUS_RESPONSE_ADC_STALE_COMPLETIONS_OFFSET = 544
STATUS_RESPONSE_ADC_RESOURCE_CONFLICTS_OFFSET = 548
STATUS_RESPONSE_ADC_START_ERRORS_OFFSET = 552
STATUS_RESPONSE_ADC_STOP_ERRORS_OFFSET = 556
STATUS_RESPONSE_ADC_STALE_INTERRUPTS_OFFSET = 560
STATUS_RESPONSE_ADC_PACKER_SOURCE_ERRORS_OFFSET = 564
STATUS_RESPONSE_ADC_PACKER_PIPELINE_ERRORS_OFFSET = 568
STATUS_RESPONSE_ADC_PACKER_CHRONOLOGY_ERRORS_OFFSET = 572
STATUS_RESPONSE_ADC_FRAMES_GENERATED_OFFSET = 576
STATUS_RESPONSE_ADC_ITEMS_GENERATED_OFFSET = 584
STATUS_RESPONSE_ADC_FRAMES_FRAMED_PIPELINE_OFFSET = 592
STATUS_RESPONSE_ADC_ITEMS_FRAMED_PIPELINE_OFFSET = 600
STATUS_RESPONSE_ADC_ITEMS_EMITTED_OFFSET = 608
STATUS_RESPONSE_ADC_FRAMES_TRANSMITTED_OFFSET = 616
STATUS_RESPONSE_ADC_ITEMS_TRANSMITTED_PIPELINE_OFFSET = 624
STATUS_RESPONSE_ADC_FRAMES_DROPPED_OFFSET = 632
STATUS_RESPONSE_GPIO_FRAMES_GENERATED_OFFSET = 640
STATUS_RESPONSE_GPIO_ITEMS_GENERATED_OFFSET = 648
STATUS_RESPONSE_GPIO_FRAMES_FRAMED_PIPELINE_OFFSET = 656
STATUS_RESPONSE_GPIO_ITEMS_FRAMED_PIPELINE_OFFSET = 664
STATUS_RESPONSE_GPIO_ITEMS_EMITTED_OFFSET = 672
STATUS_RESPONSE_GPIO_FRAMES_TRANSMITTED_OFFSET = 680
STATUS_RESPONSE_GPIO_ITEMS_TRANSMITTED_PIPELINE_OFFSET = 688
STATUS_RESPONSE_GPIO_FRAMES_DROPPED_OFFSET = 696
STATUS_RESPONSE_ADC_PAYLOAD_BYTES_PRODUCED_OFFSET = 704
STATUS_RESPONSE_ADC_PAYLOAD_BYTES_FRAMED_OFFSET = 712
STATUS_RESPONSE_ADC_PAYLOAD_BYTES_EMITTED_OFFSET = 720
STATUS_RESPONSE_ADC_PAYLOAD_BYTES_TRANSMITTED_OFFSET = 728
STATUS_RESPONSE_ADC_PAYLOAD_BYTES_DROPPED_OFFSET = 736
STATUS_RESPONSE_ADC_FRAMED_BYTES_FRAMED_OFFSET = 744
STATUS_RESPONSE_ADC_FRAMED_BYTES_EMITTED_OFFSET = 752
STATUS_RESPONSE_ADC_FRAMED_BYTES_TRANSMITTED_OFFSET = 760
STATUS_RESPONSE_GPIO_PAYLOAD_BYTES_PRODUCED_OFFSET = 768
STATUS_RESPONSE_GPIO_PAYLOAD_BYTES_FRAMED_OFFSET = 776
STATUS_RESPONSE_GPIO_PAYLOAD_BYTES_EMITTED_OFFSET = 784
STATUS_RESPONSE_GPIO_PAYLOAD_BYTES_TRANSMITTED_OFFSET = 792
STATUS_RESPONSE_GPIO_PAYLOAD_BYTES_DROPPED_OFFSET = 800
STATUS_RESPONSE_GPIO_FRAMED_BYTES_FRAMED_OFFSET = 808
STATUS_RESPONSE_GPIO_FRAMED_BYTES_EMITTED_OFFSET = 816
STATUS_RESPONSE_GPIO_FRAMED_BYTES_TRANSMITTED_OFFSET = 824
STATUS_RESPONSE_ADC_PACKET_READY_DEPTH_OFFSET = 832
STATUS_RESPONSE_GPIO_PACKET_READY_DEPTH_OFFSET = 834
STATUS_RESPONSE_ADC_PACKET_TRANSMIT_DEPTH_OFFSET = 836
STATUS_RESPONSE_GPIO_PACKET_TRANSMIT_DEPTH_OFFSET = 838
STATUS_RESPONSE_ADC_PACKET_READY_HIGH_WATER_OFFSET = 840
STATUS_RESPONSE_GPIO_PACKET_READY_HIGH_WATER_OFFSET = 842
STATUS_RESPONSE_ADC_PACKET_TRANSMIT_HIGH_WATER_OFFSET = 844
STATUS_RESPONSE_GPIO_PACKET_TRANSMIT_HIGH_WATER_OFFSET = 846
STATUS_RESPONSE_PACKET_READY_HIGH_WATER_OFFSET = 848
STATUS_RESPONSE_PACKET_TRANSMIT_HIGH_WATER_OFFSET = 850
STATUS_RESPONSE_PACKET_FRAMES_PROMOTED_OFFSET = 852
STATUS_RESPONSE_PACKET_FAIRNESS_DEFERRALS_OFFSET = 860
STATUS_RESPONSE_PACKET_ACCOUNTED_FRAME_SKEW_OFFSET = 868
STATUS_RESPONSE_DATA_PAYLOAD_BYTES_TRANSMITTED_OFFSET = 876
STATUS_RESPONSE_DATA_FRAMED_BYTES_TRANSMITTED_OFFSET = 884
STATUS_RESPONSE_PACKET_POOL_EXHAUSTIONS_OFFSET = 892
STATUS_RESPONSE_PACKET_INVALID_OPERATIONS_OFFSET = 896
STATUS_RESPONSE_PACKET_ENCODING_REJECTIONS_OFFSET = 900
STATUS_RESPONSE_PACKET_READY_QUEUE_REJECTIONS_OFFSET = 904
STATUS_RESPONSE_PACKET_TRANSMIT_QUEUE_REJECTIONS_OFFSET = 908
STATUS_RESPONSE_COMMANDS_ACCEPTED_OFFSET = 912
STATUS_RESPONSE_COMMANDS_REJECTED_OFFSET = 916
STATUS_RESPONSE_BAD_CHECKSUMS_OFFSET = 920
STATUS_RESPONSE_BAD_LENGTHS_OFFSET = 924
STATUS_RESPONSE_BAD_TYPES_OFFSET = 928
STATUS_RESPONSE_BAD_VERSIONS_OFFSET = 932
STATUS_RESPONSE_TIMEOUTS_OFFSET = 936
STATUS_RESPONSE_PARTIAL_USB_WRITES_OFFSET = 940
STATUS_RESPONSE_STATE_ERRORS_OFFSET = 944
STATUS_RESPONSE_USB_SHORT_CAPACITY_DEFERRALS_OFFSET = 948
STATUS_RESPONSE_USB_RX_STALL_EVENTS_OFFSET = 952
STATUS_RESPONSE_USB_TX_STALL_EVENTS_OFFSET = 956
STATUS_RESPONSE_USB_IO_ERRORS_OFFSET = 960
STATUS_RESPONSE_USB_COMMAND_QUEUE_DEPTH_OFFSET = 964
STATUS_RESPONSE_USB_RESPONSE_QUEUE_DEPTH_OFFSET = 966
STATUS_RESPONSE_USB_LOWER_PRIORITY_QUEUE_DEPTH_OFFSET = 968
STATUS_RESPONSE_USB_COMMAND_QUEUE_HIGH_WATER_OFFSET = 970
STATUS_RESPONSE_USB_RESPONSE_QUEUE_HIGH_WATER_OFFSET = 972
STATUS_RESPONSE_USB_ACTIVE_FRAME_BYTES_SENT_OFFSET = 974
STATUS_RESPONSE_PACKET_OWNED_DEPTH_OFFSET = 976
STATUS_RESPONSE_USB_ACTIVE_FRAME_SIZE_OFFSET = 978
STATUS_RESPONSE_ADC_CACHE_DMA_DISCARDS_OFFSET = 980
STATUS_RESPONSE_ADC_CACHE_CPU_INVALIDATIONS_OFFSET = 984
STATUS_RESPONSE_GPIO_CACHE_DMA_DISCARDS_OFFSET = 988
STATUS_RESPONSE_GPIO_CACHE_CPU_INVALIDATIONS_OFFSET = 992
STATUS_RESPONSE_BAD_FLAGS_OFFSET = 996
STATUS_RESPONSE_BAD_PAYLOADS_OFFSET = 1000
STATUS_RESPONSE_BAD_REQUEST_IDS_OFFSET = 1004
STATUS_RESPONSE_RESPONSES_QUEUED_OFFSET = 1008
STATUS_RESPONSE_RESPONSES_COMPLETED_OFFSET = 1012
STATUS_RESPONSE_RESPONSE_QUEUE_REJECTIONS_OFFSET = 1016
STATUS_RESPONSE_RESPONSE_RESERVATIONS_ABANDONED_OFFSET = 1020
STATUS_RESPONSE_PACKET_PRESSURE_EVICTIONS_OFFSET = 1024
STATUS_RESPONSE_PACKET_CAPACITY_DROPS_WITHOUT_EVICTABLE_FRAME_OFFSET = 1032
STATUS_RESPONSE_ADC_FRAMES_EVICTED_OFFSET = 1040
STATUS_RESPONSE_ADC_FRAMES_EVICTED_AFTER_PROMOTION_OFFSET = 1048
STATUS_RESPONSE_GPIO_FRAMES_EVICTED_OFFSET = 1056
STATUS_RESPONSE_GPIO_FRAMES_EVICTED_AFTER_PROMOTION_OFFSET = 1064
STATUS_RESPONSE_ADC_PACKET_FILLING_DEPTH_OFFSET = 1072
STATUS_RESPONSE_GPIO_PACKET_FILLING_DEPTH_OFFSET = 1074
STATUS_RESPONSE_ADC_FRAMES_DROPPED_AFTER_FRAMING_OFFSET = 1076
STATUS_RESPONSE_ADC_FRAMES_DROPPED_AFTER_PROMOTION_OFFSET = 1084
STATUS_RESPONSE_GPIO_FRAMES_DROPPED_AFTER_FRAMING_OFFSET = 1092
STATUS_RESPONSE_GPIO_FRAMES_DROPPED_AFTER_PROMOTION_OFFSET = 1100
STATUS_RESPONSE_GPIO_BUFFERS_COMPLETED_OFFSET = 1108
STATUS_RESPONSE_GPIO_BUFFERS_ACQUIRED_OFFSET = 1116
STATUS_RESPONSE_GPIO_BUFFERS_RELEASED_OFFSET = 1124
STATUS_RESPONSE_GPIO_SAMPLES_DELIVERED_OFFSET = 1132
STATUS_RESPONSE_GPIO_STOP_SAMPLES_DISCARDED_OFFSET = 1140
STATUS_RESPONSE_GPIO_FRAMES_PRODUCED_OFFSET = 1148
STATUS_RESPONSE_GPIO_SAMPLES_PRODUCED_OFFSET = 1156
STATUS_RESPONSE_GPIO_FRAMES_PACKED_OFFSET = 1164
STATUS_RESPONSE_GPIO_DUPLICATE_SAMPLES_IGNORED_OFFSET = 1172
STATUS_RESPONSE_ADC_FRAMES_CONSUMED_OFFSET = 1180
STATUS_RESPONSE_ADC_PAIRS_CONSUMED_OFFSET = 1188
STATUS_RESPONSE_ADC_RAW_GAP_PAIRS_OFFSET = 1196
STATUS_RESPONSE_ADC_RAW_DROP_PAIRS_PROJECTED_OFFSET = 1204
STATUS_RESPONSE_GPIO_RAW_DROP_SAMPLES_PROJECTED_OFFSET = 1212
STATUS_RESPONSE_GPIO_PACKER_DROP_SAMPLES_PROJECTED_OFFSET = 1220
STOP_RESPONSE_PAYLOAD_SIZE = 8
STOP_RESPONSE_RESPONSE_STATUS_OFFSET = 0
STOP_RESPONSE_RESERVED_0_OFFSET = 1
STOP_RESPONSE_ERROR_CODE_OFFSET = 2
STOP_RESPONSE_DEVICE_STATE_OFFSET = 4
STOP_RESPONSE_RESERVED_1_OFFSET = 5
STOP_RESPONSE_RESERVED_2_OFFSET = 6
RESET_STATS_RESPONSE_PAYLOAD_SIZE = 8
RESET_STATS_RESPONSE_RESPONSE_STATUS_OFFSET = 0
RESET_STATS_RESPONSE_RESERVED_OFFSET = 1
RESET_STATS_RESPONSE_ERROR_CODE_OFFSET = 2
RESET_STATS_RESPONSE_STATS_GENERATION_OFFSET = 4
PING_REQUEST_PAYLOAD_SIZE = 8
PING_REQUEST_NONCE_OFFSET = 0
PING_RESPONSE_PAYLOAD_SIZE = 12
PING_RESPONSE_RESPONSE_STATUS_OFFSET = 0
PING_RESPONSE_RESERVED_OFFSET = 1
PING_RESPONSE_ERROR_CODE_OFFSET = 2
PING_RESPONSE_NONCE_OFFSET = 4
CHECKSUM_BENCHMARK_REQUEST_PAYLOAD_SIZE = 8
CHECKSUM_BENCHMARK_REQUEST_CHECKSUM_ALGORITHM_OFFSET = 0
CHECKSUM_BENCHMARK_REQUEST_VECTOR_OFFSET = 1
CHECKSUM_BENCHMARK_REQUEST_MEMORY_REGION_OFFSET = 2
CHECKSUM_BENCHMARK_REQUEST_CACHE_STATE_OFFSET = 3
CHECKSUM_BENCHMARK_REQUEST_BATCH_COUNT_OFFSET = 4
CHECKSUM_BENCHMARK_REQUEST_ITERATIONS_PER_BATCH_OFFSET = 6
CHECKSUM_BENCHMARK_RESPONSE_PAYLOAD_SIZE = 96
CHECKSUM_BENCHMARK_RESPONSE_RESPONSE_STATUS_OFFSET = 0
CHECKSUM_BENCHMARK_RESPONSE_RESERVED_OFFSET = 1
CHECKSUM_BENCHMARK_RESPONSE_ERROR_CODE_OFFSET = 2
CHECKSUM_BENCHMARK_RESPONSE_CHECKSUM_ALGORITHM_OFFSET = 4
CHECKSUM_BENCHMARK_RESPONSE_VECTOR_OFFSET = 5
CHECKSUM_BENCHMARK_RESPONSE_MEMORY_REGION_OFFSET = 6
CHECKSUM_BENCHMARK_RESPONSE_CACHE_STATE_OFFSET = 7
CHECKSUM_BENCHMARK_RESPONSE_BATCH_COUNT_OFFSET = 8
CHECKSUM_BENCHMARK_RESPONSE_ITERATIONS_PER_BATCH_OFFSET = 10
CHECKSUM_BENCHMARK_RESPONSE_BUFFER_BYTES_OFFSET = 12
CHECKSUM_BENCHMARK_RESPONSE_CYCLE_COUNTER_HZ_OFFSET = 16
CHECKSUM_BENCHMARK_RESPONSE_TIMER_OVERHEAD_CYCLES_OFFSET = 20
CHECKSUM_BENCHMARK_RESPONSE_IMPLEMENTATION_CODE_BYTES_OFFSET = 24
CHECKSUM_BENCHMARK_RESPONSE_TABLE_BYTES_OFFSET = 28
CHECKSUM_BENCHMARK_RESPONSE_WORKING_RAM_BYTES_OFFSET = 32
CHECKSUM_BENCHMARK_RESPONSE_DETERMINISTIC_DIGEST_OFFSET = 36
CHECKSUM_BENCHMARK_RESPONSE_PROCESSED_BYTES_OFFSET = 40
CHECKSUM_BENCHMARK_RESPONSE_RAW_CHECKSUM_CYCLES_OFFSET = 48
CHECKSUM_BENCHMARK_RESPONSE_NET_CHECKSUM_CYCLES_OFFSET = 56
CHECKSUM_BENCHMARK_RESPONSE_CACHE_SETUP_CYCLES_OFFSET = 64
CHECKSUM_BENCHMARK_RESPONSE_MIN_BATCH_CYCLES_OFFSET = 72
CHECKSUM_BENCHMARK_RESPONSE_MAX_BATCH_CYCLES_OFFSET = 76
CHECKSUM_BENCHMARK_RESPONSE_CYCLES_PER_BYTE_Q16_OFFSET = 80
CHECKSUM_BENCHMARK_RESPONSE_MB_PER_SECOND_Q16_OFFSET = 84
CHECKSUM_BENCHMARK_RESPONSE_PROJECTED_CPU_PERCENT_Q16_OFFSET = 88
CHECKSUM_BENCHMARK_RESPONSE_TARGET_FRAMED_BYTES_PER_SECOND_OFFSET = 92
GPIO_CLOCK_DIAGNOSTIC_REQUEST_PAYLOAD_SIZE = 8
GPIO_CLOCK_DIAGNOSTIC_REQUEST_RATE_HZ_OFFSET = 0
GPIO_CLOCK_DIAGNOSTIC_REQUEST_EVENT_COUNT_OFFSET = 4
GPIO_CLOCK_DIAGNOSTIC_REQUEST_RESERVED_OFFSET = 6
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_PAYLOAD_SIZE = 140
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_RESPONSE_STATUS_OFFSET = 0
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_RESERVED_0_OFFSET = 1
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_ERROR_CODE_OFFSET = 2
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_CONFIGURED_RATE_HZ_OFFSET = 4
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_PRODUCTION_RATE_HZ_OFFSET = 8
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_PIT_CLOCK_HZ_OFFSET = 12
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_PIT_LOAD_VALUE_OFFSET = 16
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_REQUESTED_EVENT_COUNT_OFFSET = 20
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_SCHEDULED_EVENT_COUNT_OFFSET = 24
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_DMA_SAMPLE_COUNT_OFFSET = 28
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_DWT_COUNTER_HZ_OFFSET = 32
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_DWT_ELAPSED_CYCLES_OFFSET = 36
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_HARDWARE_ERROR_FLAGS_OFFSET = 40
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_CCM_CSCMR1_CONFIGURED_OFFSET = 44
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_CCM_CCGR1_CONFIGURED_OFFSET = 48
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_CCM_CCGR2_CONFIGURED_OFFSET = 52
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_CCM_CCGR5_CONFIGURED_OFFSET = 56
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_PIT_MCR_CONFIGURED_OFFSET = 60
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_PIT_LDVAL_CONFIGURED_OFFSET = 64
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_PIT_CVAL_FINAL_OFFSET = 68
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_PIT_TCTRL_CONFIGURED_OFFSET = 72
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_PIT_TFLG_FINAL_OFFSET = 76
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_XBAR_SEL_CONFIGURED_OFFSET = 80
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_XBAR_CTRL_CONFIGURED_OFFSET = 82
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_DMAMUX_CHCFG_CONFIGURED_OFFSET = 84
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_DMA_CR_CONFIGURED_OFFSET = 88
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_DMA_ES_FINAL_OFFSET = 92
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_DMA_ERQ_CONFIGURED_OFFSET = 96
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_DMA_ERR_FINAL_OFFSET = 100
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_DMA_HRS_FINAL_OFFSET = 104
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_TCD_SADDR_OFFSET = 108
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_TCD_DADDR_OFFSET = 112
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_TCD_NBYTES_OFFSET = 116
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_LAST_SAMPLE_WORD_OFFSET = 120
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_TCD_CITER_FINAL_OFFSET = 124
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_TCD_BITER_OFFSET = 126
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_TCD_CSR_FINAL_OFFSET = 128
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_TCD_ATTR_OFFSET = 130
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_PIT_CHANNEL_OFFSET = 132
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_XBAR_INPUT_OFFSET = 133
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_XBAR_OUTPUT_OFFSET = 134
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_EDMA_CHANNEL_OFFSET = 135
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_DMAMUX_SOURCE_OFFSET = 136
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_EDMA_PRIORITY_OFFSET = 137
GPIO_CLOCK_DIAGNOSTIC_RESPONSE_TCD_SOFF_OFFSET = 138
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_PAYLOAD_SIZE = 144
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_RESPONSE_STATUS_OFFSET = 0
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_RESERVED_0_OFFSET = 1
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_ERROR_CODE_OFFSET = 2
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_MODE_OFFSET = 4
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_METADATA_KIND_OFFSET = 5
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_DRIVE_SAFETY_OFFSET = 6
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_STIMULUS_KIND_OFFSET = 7
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_FIXTURE_IDENTITY_OFFSET = 8
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_STIMULUS_IDENTITY_OFFSET = 12
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_HARDWARE_ERROR_FLAGS_OFFSET = 16
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_DIAGNOSTIC_FLAGS_OFFSET = 20
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_DWT_COUNTER_HZ_OFFSET = 24
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_DWT_ELAPSED_CYCLES_OFFSET = 28
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_DMA_SAMPLES_CAPTURED_OFFSET = 32
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_COMPLETE_SAMPLES_RETAINED_OFFSET = 40
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_SAMPLES_ANALYZED_OFFSET = 44
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_STOPPED_PARTIAL_SAMPLES_OFFSET = 48
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_RAW_WORD_AND_OFFSET = 52
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_RAW_WORD_OR_OFFSET = 56
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_OBSERVED_TRANSITIONS_OFFSET = 60
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_MAPPING_VALUES_CHECKED_OFFSET = 64
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_MAPPING_FAILURES_OFFSET = 66
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_UNSTABLE_SAMPLES_OFFSET = 68
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_RESERVED_1_OFFSET = 70
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_PACKED_VALUE_AND_OFFSET = 72
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_PACKED_VALUE_OR_OFFSET = 73
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_FIRST_PACKED_VALUE_OFFSET = 74
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_LAST_PACKED_VALUE_OFFSET = 75
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_GPR27_BEFORE_OFFSET = 76
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_GPR27_CONFIGURED_OFFSET = 80
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_GPR27_AFTER_OFFSET = 84
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_GPIO2_GDIR_BEFORE_OFFSET = 88
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_GPIO2_GDIR_CONFIGURED_OFFSET = 92
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_GPIO2_GDIR_AFTER_OFFSET = 96
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_GPIO2_PSR_BEFORE_OFFSET = 100
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_GPIO2_PSR_CONFIGURED_OFFSET = 104
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_GPIO2_PSR_AFTER_OFFSET = 108
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_PIT_LDVAL_CONFIGURED_OFFSET = 112
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_PIT_TCTRL_CONFIGURED_OFFSET = 116
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_DMAMUX_CHCFG_CONFIGURED_OFFSET = 120
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_DMA_ERQ_CONFIGURED_OFFSET = 124
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_DMA_ERR_FINAL_OFFSET = 128
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_TCD_CITER_CONFIGURED_OFFSET = 132
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_TCD_BITER_CONFIGURED_OFFSET = 134
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_TCD_CSR_CONFIGURED_OFFSET = 136
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_EDMA_PRIORITY_CONFIGURED_OFFSET = 138
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_RESERVED_2_OFFSET = 139
GPIO_CAPTURE_DIAGNOSTIC_RESPONSE_ANALYSIS_SAMPLE_LIMIT_OFFSET = 140
ERROR_RESPONSE_PAYLOAD_SIZE = 8
ERROR_RESPONSE_RESPONSE_STATUS_OFFSET = 0
ERROR_RESPONSE_RESERVED_0_OFFSET = 1
ERROR_RESPONSE_ERROR_CODE_OFFSET = 2
ERROR_RESPONSE_REJECTED_KIND_OFFSET = 4
ERROR_RESPONSE_REJECTED_VERSION_OFFSET = 5
ERROR_RESPONSE_RESERVED_1_OFFSET = 6
OUTPUT_BEGIN_REQUEST_PAYLOAD_SIZE = 8
OUTPUT_BEGIN_REQUEST_REPEAT_COUNT_OFFSET = 0
OUTPUT_BEGIN_REQUEST_IDLE_STATE_MASK_OFFSET = 4
OUTPUT_APPEND_REQUEST_PAYLOAD_SIZE = 8
OUTPUT_APPEND_REQUEST_DURATION_SAMPLES_OFFSET = 0
OUTPUT_APPEND_REQUEST_LOGICAL_STATE_MASK_OFFSET = 4
OUTPUT_COMMIT_REQUEST_PAYLOAD_SIZE = 8
OUTPUT_COMMIT_REQUEST_SEGMENT_COUNT_OFFSET = 0
OUTPUT_COMMIT_REQUEST_PROGRAM_CHECKSUM_OFFSET = 4
OUTPUT_APPEND_RESPONSE_PAYLOAD_SIZE = 16
OUTPUT_APPEND_RESPONSE_RESPONSE_STATUS_OFFSET = 0
OUTPUT_APPEND_RESPONSE_RESERVED_OFFSET = 1
OUTPUT_APPEND_RESPONSE_ERROR_CODE_OFFSET = 2
OUTPUT_APPEND_RESPONSE_ACCEPTED_SEGMENT_COUNT_OFFSET = 4
OUTPUT_APPEND_RESPONSE_DURATION_SAMPLES_OFFSET = 8
OUTPUT_APPEND_RESPONSE_LOGICAL_STATE_MASK_OFFSET = 12
OUTPUT_STATUS_RESPONSE_PAYLOAD_SIZE = 224
OUTPUT_STATUS_RESPONSE_RESPONSE_STATUS_OFFSET = 0
OUTPUT_STATUS_RESPONSE_RESERVED_0_OFFSET = 1
OUTPUT_STATUS_RESPONSE_ERROR_CODE_OFFSET = 2
OUTPUT_STATUS_RESPONSE_OUTPUT_STATE_OFFSET = 4
OUTPUT_STATUS_RESPONSE_OUTPUT_BANK_MODE_OFFSET = 5
OUTPUT_STATUS_RESPONSE_FAULT_LATCHED_OFFSET = 6
OUTPUT_STATUS_RESPONSE_RESERVED_1_OFFSET = 7
OUTPUT_STATUS_RESPONSE_GENERATION_OFFSET = 8
OUTPUT_STATUS_RESPONSE_IDLE_STATE_MASK_OFFSET = 12
OUTPUT_STATUS_RESPONSE_CURRENT_STATE_MASK_OFFSET = 16
OUTPUT_STATUS_RESPONSE_LAST_EMITTED_STATE_MASK_OFFSET = 20
OUTPUT_STATUS_RESPONSE_REPEAT_COUNT_OFFSET = 24
OUTPUT_STATUS_RESPONSE_COMPLETED_REPEATS_OFFSET = 28
OUTPUT_STATUS_RESPONSE_SEGMENT_COUNT_OFFSET = 32
OUTPUT_STATUS_RESPONSE_ACCEPTED_SEGMENT_COUNT_OFFSET = 36
OUTPUT_STATUS_RESPONSE_PROGRAM_CHECKSUM_OFFSET = 40
OUTPUT_STATUS_RESPONSE_CURRENT_SEGMENT_INDEX_OFFSET = 44
OUTPUT_STATUS_RESPONSE_TICKS_ELAPSED_OFFSET = 48
OUTPUT_STATUS_RESPONSE_TRANSITIONS_EMITTED_OFFSET = 56
OUTPUT_STATUS_RESPONSE_OUTPUT_ERROR_OFFSET = 60
OUTPUT_STATUS_RESPONSE_RESERVED_2_OFFSET = 61
OUTPUT_STATUS_RESPONSE_RESERVED_3_OFFSET = 62
OUTPUT_STATUS_RESPONSE_CURRENT_SEGMENT_REMAINING_OFFSET = 64
OUTPUT_STATUS_RESPONSE_COMMON_RUN_ID_OFFSET = 68
OUTPUT_STATUS_RESPONSE_REQUESTED_DURATION_STATES_OFFSET = 72
OUTPUT_STATUS_RESPONSE_STATES_EXPANDED_OFFSET = 80
OUTPUT_STATUS_RESPONSE_DMA_STATES_QUEUED_OFFSET = 88
OUTPUT_STATUS_RESPONSE_DMA_STATES_EMITTED_OFFSET = 96
OUTPUT_STATUS_RESPONSE_HELD_REMAINDER_STATES_OFFSET = 104
OUTPUT_STATUS_RESPONSE_BLOCKS_FILLED_OFFSET = 112
OUTPUT_STATUS_RESPONSE_BLOCKS_COMPLETED_OFFSET = 120
OUTPUT_STATUS_RESPONSE_START_TICK_OFFSET = 128
OUTPUT_STATUS_RESPONSE_COMPLETION_TICK_OFFSET = 136
OUTPUT_STATUS_RESPONSE_HOLD_TICK_OFFSET = 144
OUTPUT_STATUS_RESPONSE_READY_DEPTH_OFFSET = 152
OUTPUT_STATUS_RESPONSE_READY_HIGH_WATER_OFFSET = 154
OUTPUT_STATUS_RESPONSE_REFILL_LEAD_OFFSET = 156
OUTPUT_STATUS_RESPONSE_REFILL_LEAD_HIGH_WATER_OFFSET = 160
OUTPUT_STATUS_RESPONSE_CACHE_FLUSHES_OFFSET = 164
OUTPUT_STATUS_RESPONSE_START_OPERATIONS_OFFSET = 168
OUTPUT_STATUS_RESPONSE_STOP_OPERATIONS_OFFSET = 172
OUTPUT_STATUS_RESPONSE_INVALID_OPERATIONS_OFFSET = 176
OUTPUT_STATUS_RESPONSE_RESOURCE_CONFLICTS_OFFSET = 180
OUTPUT_STATUS_RESPONSE_UNDERRUNS_OFFSET = 184
OUTPUT_STATUS_RESPONSE_STALE_COMPLETIONS_OFFSET = 188
OUTPUT_STATUS_RESPONSE_DMA_ERRORS_OFFSET = 192
OUTPUT_STATUS_RESPONSE_START_ERRORS_OFFSET = 196
OUTPUT_STATUS_RESPONSE_STOP_ERRORS_OFFSET = 200
OUTPUT_STATUS_RESPONSE_CONSERVATION_ERRORS_OFFSET = 204
OUTPUT_STATUS_RESPONSE_CONSERVATION_EXACT_OFFSET = 208
OUTPUT_STATUS_RESPONSE_RESERVED_4_OFFSET = 209
OUTPUT_STATUS_RESPONSE_RESERVED_5_OFFSET = 210
OUTPUT_STATUS_RESPONSE_RESERVED_6_OFFSET = 212
OUTPUT_STATUS_RESPONSE_RESERVED_7_OFFSET = 216
