#pragma once

#include <cstddef>
#include <cstdint>

#include "firmware_identity.h"
#include "usb_transport.h"

namespace thingdaq::usb {

inline constexpr std::uint16_t kTeensyUsbSerialVendorId = 0x16C0U;
inline constexpr std::uint16_t kTeensyUsbSerialProductId = 0x0483U;
inline constexpr std::uint8_t kUsbStringDescriptorType = 3U;

// Decode the decimal UTF-16LE code units generated by the Teensy core from
// the chip fuse. This gives INFO the same numeric identity as USB enumeration
// without replacing or independently formatting the serial descriptor.
bool parseDecimalHardwareSerial(const std::uint16_t *code_units,
                                std::size_t code_unit_count,
                                std::uint32_t &hardware_serial);

#if defined(ARDUINO_TEENSY40) && defined(__IMXRT1062__)

class TeensyCdcByteStream final : public CdcByteStream {
 public:
  bool sessionOpen() const override;
  IoCount available() override;
  IoCount read(std::uint8_t *destination, std::size_t capacity) override;
  IoCount availableForWrite() override;
  IoCount write(const std::uint8_t *source, std::size_t size) override;
};

std::uint32_t hardwareSerialNumber();

#endif

}  // namespace thingdaq::usb
