"""Generated protocol-v1 constants. Do not edit by hand.

Source: protocol/protocol-v1.json
Source SHA-256: 08a7ac4ddb3b8d397b5f0ff87f4aac41c31c3b780fb3e25d2af4c68ba9b02ae6
"""

from __future__ import annotations

from enum import IntEnum, IntFlag

SOURCE_SHA256 = "08a7ac4ddb3b8d397b5f0ff87f4aac41c31c3b780fb3e25d2af4c68ba9b02ae6"
MAGIC = 0xDEADBEEF
MAGIC_BYTES = b"\xef\xbe\xad\xde"
PROTOCOL_VERSION = 1
BYTE_ORDER = "little"
HEADER_STRUCT_FORMAT = "<IBBHHBBIIIIIQI"
HEADER_SIZE = 44
TRAILER_SIZE = 4
MIN_FRAME_BYTES = 48
DATA_FRAME_BYTES = 4096
DATA_PAYLOAD_BYTES = 4048
MAX_CONTROL_FRAME_BYTES = 1024
MAX_CONTROL_PAYLOAD_BYTES = MAX_CONTROL_FRAME_BYTES - HEADER_SIZE - TRAILER_SIZE
TIMESTAMP_HZ = 8000000
ADC_PAIR_RATE_HZ = 1000000
ADC_PAIR_PERIOD_TICKS = 8
ADC1_PHASE_TICKS = 4
GPIO_SAMPLE_RATE_HZ = 4000000
GPIO_SAMPLE_PERIOD_TICKS = 2
FRAME_COVERAGE_TICKS = 8096
ADC_BYTES_PER_PAIR = 4
ADC_PAIRS_PER_FRAME = 1012
ADC_RESOLUTION_BITS = 12
ADC_CONTAINER_BITS = 16
GPIO_SAMPLES_PER_FRAME = 4048
GPIO_PINS_BY_BIT = (6, 7, 8, 9, 10, 11, 12, 13)
UINT32_MAX = 0xFFFFFFFF
UINT64_MAX = 0xFFFFFFFFFFFFFFFF


HEADER_MAGIC_OFFSET = 0
HEADER_VERSION_OFFSET = 4
HEADER_KIND_OFFSET = 5
HEADER_FLAGS_OFFSET = 6
HEADER_HEADER_LENGTH_OFFSET = 8
HEADER_CHECKSUM_ALGORITHM_OFFSET = 10
HEADER_RESERVED_OFFSET = 11
HEADER_TOTAL_LENGTH_OFFSET = 12
HEADER_PAYLOAD_LENGTH_OFFSET = 16
HEADER_RUN_ID_OFFSET = 20
HEADER_SEQUENCE_OFFSET = 24
HEADER_REQUEST_ID_OFFSET = 28
HEADER_FIRST_SAMPLE_TICKS_OFFSET = 32
HEADER_ITEM_COUNT_OFFSET = 40


class FrameKind(IntEnum):
    ADC_DATA = 1
    GPIO_DATA = 2
    INFO_REQUEST = 16
    CONFIGURE_REQUEST = 17
    START_REQUEST = 18
    STATUS_REQUEST = 19
    STOP_REQUEST = 20
    INFO_RESPONSE = 144
    CONFIGURE_RESPONSE = 145
    START_RESPONSE = 146
    STATUS_RESPONSE = 147
    STOP_RESPONSE = 148
    ERROR_RESPONSE = 159


class FrameFlag(IntFlag):
    NONE = 0
    SYNTHETIC = 1
    GAP_BEFORE = 2
    EPOCH_START = 4
    RESPONSE_ERROR = 32768


class ChecksumAlgorithm(IntEnum):
    NONE_RESERVED = 0
    ADLER32 = 1
    CRC32C = 2


class ResponseStatus(IntEnum):
    OK = 0
    ERROR = 1


class ErrorCode(IntEnum):
    OK = 0
    UNSUPPORTED_VERSION = 1
    UNKNOWN_FRAME_KIND = 2
    INVALID_FLAGS = 3
    INVALID_LENGTH = 4
    INVALID_PAYLOAD = 5
    UNSUPPORTED_CHECKSUM = 6
    INVALID_STATE = 7
    UNSUPPORTED_CONFIGURATION = 8
    INVALID_REQUEST_ID = 9
    BUSY = 10
    INTERNAL_ERROR = 11
    CHECKSUM_MISMATCH = 12


class DeviceState(IntEnum):
    BOOT = 0
    IDLE = 1
    CONFIGURED = 2
    RUNNING = 3


class StreamMask(IntFlag):
    NONE = 0
    ADC = 1
    GPIO = 2


class Source(IntEnum):
    HARDWARE = 0
    SYNTHETIC = 1


class BoardId(IntEnum):
    SIMULATOR = 0
    TEENSY_40 = 1


class McuId(IntEnum):
    SIMULATED = 0
    IMXRT1062 = 1


DEFAULT_CHECKSUM_ALGORITHM = ChecksumAlgorithm.ADLER32
SUPPORTED_CHECKSUM_ALGORITHMS = frozenset(
    {
        ChecksumAlgorithm.ADLER32,
    }
)

SUPPORTED_CHECKSUM_MASK = 2


FRAME_KIND_CLASS: dict[FrameKind, str] = {
    FrameKind.ADC_DATA: "data",
    FrameKind.GPIO_DATA: "data",
    FrameKind.INFO_REQUEST: "request",
    FrameKind.CONFIGURE_REQUEST: "request",
    FrameKind.START_REQUEST: "request",
    FrameKind.STATUS_REQUEST: "request",
    FrameKind.STOP_REQUEST: "request",
    FrameKind.INFO_RESPONSE: "response",
    FrameKind.CONFIGURE_RESPONSE: "response",
    FrameKind.START_RESPONSE: "response",
    FrameKind.STATUS_RESPONSE: "response",
    FrameKind.STOP_RESPONSE: "response",
    FrameKind.ERROR_RESPONSE: "error_response",
}

ALLOWED_FLAGS_BY_KIND: dict[FrameKind, FrameFlag] = {
    FrameKind.ADC_DATA: FrameFlag.SYNTHETIC
    | FrameFlag.GAP_BEFORE
    | FrameFlag.EPOCH_START,
    FrameKind.GPIO_DATA: FrameFlag.SYNTHETIC
    | FrameFlag.GAP_BEFORE
    | FrameFlag.EPOCH_START,
    FrameKind.INFO_REQUEST: FrameFlag.NONE,
    FrameKind.CONFIGURE_REQUEST: FrameFlag.NONE,
    FrameKind.START_REQUEST: FrameFlag.NONE,
    FrameKind.STATUS_REQUEST: FrameFlag.NONE,
    FrameKind.STOP_REQUEST: FrameFlag.NONE,
    FrameKind.INFO_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.CONFIGURE_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.START_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.STATUS_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.STOP_RESPONSE: FrameFlag.RESPONSE_ERROR,
    FrameKind.ERROR_RESPONSE: FrameFlag.RESPONSE_ERROR,
}

REQUEST_RESPONSE_KIND: dict[FrameKind, FrameKind] = {
    FrameKind.INFO_REQUEST: FrameKind.INFO_RESPONSE,
    FrameKind.CONFIGURE_REQUEST: FrameKind.CONFIGURE_RESPONSE,
    FrameKind.START_REQUEST: FrameKind.START_RESPONSE,
    FrameKind.STATUS_REQUEST: FrameKind.STATUS_RESPONSE,
    FrameKind.STOP_REQUEST: FrameKind.STOP_RESPONSE,
}

PAYLOAD_SIZE_BY_SCHEMA: dict[str, int] = {
    "empty": 0,
    "adc_data": 4048,
    "gpio_data": 4048,
    "configure_request": 8,
    "response_prefix": 4,
    "info_response": 94,
    "configure_response": 12,
    "status_response": 52,
    "stop_response": 8,
    "error_response": 8,
}

EMPTY_PAYLOAD_SIZE = 0
ADC_DATA_PAYLOAD_SIZE = 4048
ADC_DATA_PAIRS_OFFSET = 0
ADC_DATA_PAIRS_COUNT = 1012
GPIO_DATA_PAYLOAD_SIZE = 4048
GPIO_DATA_SAMPLES_OFFSET = 0
GPIO_DATA_SAMPLES_COUNT = 4048
CONFIGURE_REQUEST_PAYLOAD_SIZE = 8
CONFIGURE_REQUEST_STREAM_MASK_OFFSET = 0
CONFIGURE_REQUEST_SOURCE_OFFSET = 1
CONFIGURE_REQUEST_DATA_CHECKSUM_ALGORITHM_OFFSET = 2
CONFIGURE_REQUEST_RESERVED_OFFSET = 3
CONFIGURE_REQUEST_DATA_FRAME_BYTES_OFFSET = 4
RESPONSE_PREFIX_PAYLOAD_SIZE = 4
RESPONSE_PREFIX_RESPONSE_STATUS_OFFSET = 0
RESPONSE_PREFIX_RESERVED_OFFSET = 1
RESPONSE_PREFIX_ERROR_CODE_OFFSET = 2
INFO_RESPONSE_PAYLOAD_SIZE = 94
INFO_RESPONSE_RESPONSE_STATUS_OFFSET = 0
INFO_RESPONSE_RESERVED_0_OFFSET = 1
INFO_RESPONSE_ERROR_CODE_OFFSET = 2
INFO_RESPONSE_DEVICE_STATE_OFFSET = 4
INFO_RESPONSE_PROTOCOL_VERSION_OFFSET = 5
INFO_RESPONSE_SUPPORTED_STREAM_MASK_OFFSET = 6
INFO_RESPONSE_SUPPORTED_SOURCE_MASK_OFFSET = 7
INFO_RESPONSE_SUPPORTED_CHECKSUM_MASK_OFFSET = 8
INFO_RESPONSE_TIMESTAMP_HZ_OFFSET = 12
INFO_RESPONSE_DATA_FRAME_BYTES_OFFSET = 16
INFO_RESPONSE_MAX_CONTROL_FRAME_BYTES_OFFSET = 20
INFO_RESPONSE_ADC_PAIR_RATE_HZ_OFFSET = 24
INFO_RESPONSE_GPIO_SAMPLE_RATE_HZ_OFFSET = 28
INFO_RESPONSE_ADC_PAIR_PERIOD_TICKS_OFFSET = 32
INFO_RESPONSE_ADC1_PHASE_TICKS_OFFSET = 34
INFO_RESPONSE_GPIO_SAMPLE_PERIOD_TICKS_OFFSET = 36
INFO_RESPONSE_ADC_RESOLUTION_BITS_OFFSET = 38
INFO_RESPONSE_ADC_CONTAINER_BYTES_OFFSET = 39
INFO_RESPONSE_GPIO_PIN_COUNT_OFFSET = 40
INFO_RESPONSE_RESERVED_1_OFFSET = 41
INFO_RESPONSE_GPIO_PIN_MAP_OFFSET = 42
INFO_RESPONSE_GPIO_PIN_MAP_COUNT = 8
INFO_RESPONSE_HARDWARE_SERIAL_OFFSET = 50
INFO_RESPONSE_FIRMWARE_VERSION_MAJOR_OFFSET = 54
INFO_RESPONSE_FIRMWARE_VERSION_MINOR_OFFSET = 55
INFO_RESPONSE_FIRMWARE_VERSION_PATCH_OFFSET = 56
INFO_RESPONSE_RESERVED_2_OFFSET = 57
INFO_RESPONSE_BOARD_ID_OFFSET = 58
INFO_RESPONSE_MCU_ID_OFFSET = 60
INFO_RESPONSE_BUILD_ID_OFFSET = 62
INFO_RESPONSE_BUILD_ID_COUNT = 32
CONFIGURE_RESPONSE_PAYLOAD_SIZE = 12
CONFIGURE_RESPONSE_RESPONSE_STATUS_OFFSET = 0
CONFIGURE_RESPONSE_RESERVED_0_OFFSET = 1
CONFIGURE_RESPONSE_ERROR_CODE_OFFSET = 2
CONFIGURE_RESPONSE_STREAM_MASK_OFFSET = 4
CONFIGURE_RESPONSE_SOURCE_OFFSET = 5
CONFIGURE_RESPONSE_DATA_CHECKSUM_ALGORITHM_OFFSET = 6
CONFIGURE_RESPONSE_RESERVED_1_OFFSET = 7
CONFIGURE_RESPONSE_DATA_FRAME_BYTES_OFFSET = 8
STATUS_RESPONSE_PAYLOAD_SIZE = 52
STATUS_RESPONSE_RESPONSE_STATUS_OFFSET = 0
STATUS_RESPONSE_RESERVED_OFFSET = 1
STATUS_RESPONSE_ERROR_CODE_OFFSET = 2
STATUS_RESPONSE_DEVICE_STATE_OFFSET = 4
STATUS_RESPONSE_STREAM_MASK_OFFSET = 5
STATUS_RESPONSE_SOURCE_OFFSET = 6
STATUS_RESPONSE_DATA_CHECKSUM_ALGORITHM_OFFSET = 7
STATUS_RESPONSE_DATA_FRAME_BYTES_OFFSET = 8
STATUS_RESPONSE_ADC_FRAMES_EMITTED_OFFSET = 12
STATUS_RESPONSE_GPIO_FRAMES_EMITTED_OFFSET = 20
STATUS_RESPONSE_ADC_ITEMS_DROPPED_OFFSET = 28
STATUS_RESPONSE_GPIO_ITEMS_DROPPED_OFFSET = 36
STATUS_RESPONSE_PARSER_ERRORS_OFFSET = 44
STATUS_RESPONSE_TRANSPORT_ERRORS_OFFSET = 48
STOP_RESPONSE_PAYLOAD_SIZE = 8
STOP_RESPONSE_RESPONSE_STATUS_OFFSET = 0
STOP_RESPONSE_RESERVED_0_OFFSET = 1
STOP_RESPONSE_ERROR_CODE_OFFSET = 2
STOP_RESPONSE_DEVICE_STATE_OFFSET = 4
STOP_RESPONSE_RESERVED_1_OFFSET = 5
STOP_RESPONSE_RESERVED_2_OFFSET = 6
ERROR_RESPONSE_PAYLOAD_SIZE = 8
ERROR_RESPONSE_RESPONSE_STATUS_OFFSET = 0
ERROR_RESPONSE_RESERVED_0_OFFSET = 1
ERROR_RESPONSE_ERROR_CODE_OFFSET = 2
ERROR_RESPONSE_REJECTED_KIND_OFFSET = 4
ERROR_RESPONSE_REJECTED_VERSION_OFFSET = 5
ERROR_RESPONSE_RESERVED_1_OFFSET = 6
