"""Expert-only protocol, reader, and transport building blocks.

Normal applications should use :class:`thingdaq.ThingDAQ` and the typed
models exported from :mod:`thingdaq`.  This namespace keeps raw frame and
byte-transport access available for protocol tooling without making callers
construct frames for ordinary discovery, configuration, or capture workflows.
"""

from ._generated import protocol_constants, protocol_v2_constants
from .protocol import (
    ChecksumAlgorithmMismatchError,
    ChecksumMismatchError,
    Frame,
    FrameHeader,
    FrameParser,
    FrameValidationError,
    IncrementalFrameParser,
    ParserCounters,
    ProtocolError,
    UnsupportedChecksumError,
    checksum_backend,
    compute_checksum,
    decode_frame,
    encode_frame,
)
from .protocol_v2 import (
    EncodingDiagnostics,
    IncrementalV2FrameParser,
    RawFallbackReason,
    V2EncodingNotNegotiatedError,
    V2Frame,
    V2FrameHeader,
    V2FrameValidationError,
    V2ProtocolError,
    V2RLEValidationError,
    compute_v2_checksum,
    count_rle_runs,
    decode_rle_payload,
    decode_v2_data_block,
    decode_v2_frame,
    decode_v2_message,
    encode_rle_payload,
    encode_v2_data_frame,
    encode_v2_frame,
)
from .reader import (
    DEFAULT_MAX_QUEUED_BLOCKS,
    BackgroundReader,
    DeviceDisconnectedError,
    PendingRequestLimitError,
    QueueWaitTimeoutError,
    ReaderClosedError,
    ReaderCounters,
    ReaderError,
    ReaderEvent,
    ReaderNotStartedError,
    ReaderProtocolError,
    ReaderShutdownError,
    RequestTimeoutError,
    StreamStoppedError,
)
from .transport import (
    ByteTransport,
    InMemoryTransport,
    MemoryTransport,
    SerialPortBusyError,
    SerialTransport,
    Transport,
    TransportBufferError,
    TransportClosedError,
    TransportDisconnectedError,
    TransportError,
    TransportOpenError,
    TransportTimeoutError,
)

__all__ = [
    "DEFAULT_MAX_QUEUED_BLOCKS",
    "BackgroundReader",
    "ByteTransport",
    "ChecksumAlgorithmMismatchError",
    "ChecksumMismatchError",
    "DeviceDisconnectedError",
    "EncodingDiagnostics",
    "Frame",
    "FrameHeader",
    "FrameParser",
    "FrameValidationError",
    "InMemoryTransport",
    "IncrementalFrameParser",
    "IncrementalV2FrameParser",
    "MemoryTransport",
    "ParserCounters",
    "PendingRequestLimitError",
    "ProtocolError",
    "QueueWaitTimeoutError",
    "RawFallbackReason",
    "ReaderClosedError",
    "ReaderCounters",
    "ReaderError",
    "ReaderEvent",
    "ReaderNotStartedError",
    "ReaderProtocolError",
    "ReaderShutdownError",
    "RequestTimeoutError",
    "SerialPortBusyError",
    "SerialTransport",
    "StreamStoppedError",
    "Transport",
    "TransportBufferError",
    "TransportClosedError",
    "TransportDisconnectedError",
    "TransportError",
    "TransportOpenError",
    "TransportTimeoutError",
    "UnsupportedChecksumError",
    "V2EncodingNotNegotiatedError",
    "V2Frame",
    "V2FrameHeader",
    "V2FrameValidationError",
    "V2ProtocolError",
    "V2RLEValidationError",
    "checksum_backend",
    "compute_checksum",
    "compute_v2_checksum",
    "count_rle_runs",
    "decode_frame",
    "decode_rle_payload",
    "decode_v2_data_block",
    "decode_v2_frame",
    "decode_v2_message",
    "encode_frame",
    "encode_rle_payload",
    "encode_v2_data_frame",
    "encode_v2_frame",
    "protocol_constants",
    "protocol_v2_constants",
]
