"""Protocol and data-model foundation for the Teensy DAQ project."""

from ._generated.protocol_constants import (
    BoardId,
    ChecksumAlgorithm,
    DeviceState,
    ErrorCode,
    FrameFlag,
    FrameKind,
    McuId,
    ResponseStatus,
    Source,
    StreamMask,
)
from .models import (
    ADCBlock,
    AdcBlock,
    AdcChannelView,
    AdcConverter,
    AdcSample,
    CommandResponse,
    Configuration,
    DeviceInfo,
    GPIOBlock,
    GpioBlock,
    GpioChannelView,
    Info,
    Status,
    StreamGap,
    decode_message,
    decode_response,
    extract_gpio_channel,
    interleave_adc,
)
from .protocol import (
    ChecksumMismatchError,
    Frame,
    FrameHeader,
    FrameParser,
    FrameValidationError,
    IncrementalFrameParser,
    ProtocolError,
    UnsupportedChecksumError,
    compute_checksum,
    decode_frame,
    encode_frame,
)
from .synthetic import (
    synthetic_adc0_code,
    synthetic_adc1_code,
    synthetic_adc_code,
    synthetic_adc_payload,
    synthetic_gpio_byte,
    synthetic_gpio_payload,
)

__version__ = "0.0.0"

__all__ = [
    "ADCBlock",
    "AdcBlock",
    "AdcChannelView",
    "AdcConverter",
    "AdcSample",
    "BoardId",
    "ChecksumAlgorithm",
    "ChecksumMismatchError",
    "CommandResponse",
    "Configuration",
    "DeviceInfo",
    "DeviceState",
    "ErrorCode",
    "Frame",
    "FrameFlag",
    "FrameHeader",
    "FrameKind",
    "FrameParser",
    "FrameValidationError",
    "GPIOBlock",
    "GpioBlock",
    "GpioChannelView",
    "IncrementalFrameParser",
    "Info",
    "McuId",
    "ProtocolError",
    "ResponseStatus",
    "Source",
    "Status",
    "StreamGap",
    "StreamMask",
    "UnsupportedChecksumError",
    "compute_checksum",
    "decode_frame",
    "decode_message",
    "decode_response",
    "encode_frame",
    "extract_gpio_channel",
    "interleave_adc",
    "synthetic_adc0_code",
    "synthetic_adc1_code",
    "synthetic_adc_code",
    "synthetic_adc_payload",
    "synthetic_gpio_byte",
    "synthetic_gpio_payload",
]
