"""Expert-only protocol, reader, and transport building blocks.

Normal applications should use :class:`teensy_daq.TeensyDAQ` and the typed
models exported from :mod:`teensy_daq`.  This namespace keeps raw frame and
byte-transport access available for protocol tooling without making callers
construct frames for ordinary discovery, configuration, or capture workflows.
"""

from ._generated import protocol_constants
from .protocol import (
    ChecksumAlgorithmMismatchError,
    ChecksumMismatchError,
    Frame,
    FrameHeader,
    FrameParser,
    FrameValidationError,
    IncrementalFrameParser,
    ParserCounters,
    ProtocolError,
    UnsupportedChecksumError,
    checksum_backend,
    compute_checksum,
    decode_frame,
    encode_frame,
)
from .reader import (
    DEFAULT_MAX_QUEUED_BLOCKS,
    BackgroundReader,
    DeviceDisconnectedError,
    PendingRequestLimitError,
    QueueWaitTimeoutError,
    ReaderClosedError,
    ReaderCounters,
    ReaderError,
    ReaderEvent,
    ReaderNotStartedError,
    ReaderProtocolError,
    ReaderShutdownError,
    RequestTimeoutError,
    StreamStoppedError,
)
from .transport import (
    ByteTransport,
    InMemoryTransport,
    MemoryTransport,
    SerialPortBusyError,
    SerialTransport,
    Transport,
    TransportBufferError,
    TransportClosedError,
    TransportDisconnectedError,
    TransportError,
    TransportOpenError,
    TransportTimeoutError,
)

__all__ = [
    "DEFAULT_MAX_QUEUED_BLOCKS",
    "BackgroundReader",
    "ByteTransport",
    "ChecksumAlgorithmMismatchError",
    "ChecksumMismatchError",
    "DeviceDisconnectedError",
    "Frame",
    "FrameHeader",
    "FrameParser",
    "FrameValidationError",
    "InMemoryTransport",
    "IncrementalFrameParser",
    "MemoryTransport",
    "ParserCounters",
    "PendingRequestLimitError",
    "ProtocolError",
    "QueueWaitTimeoutError",
    "ReaderClosedError",
    "ReaderCounters",
    "ReaderError",
    "ReaderEvent",
    "ReaderNotStartedError",
    "ReaderProtocolError",
    "ReaderShutdownError",
    "RequestTimeoutError",
    "SerialPortBusyError",
    "SerialTransport",
    "StreamStoppedError",
    "Transport",
    "TransportBufferError",
    "TransportClosedError",
    "TransportDisconnectedError",
    "TransportError",
    "TransportOpenError",
    "TransportTimeoutError",
    "UnsupportedChecksumError",
    "checksum_backend",
    "compute_checksum",
    "decode_frame",
    "encode_frame",
    "protocol_constants",
]
